### ISSUE TITLE
Need help with ordering menu item

### ISSUE THREAD

**Issue by nyue** [thegeeklab/hugo-geekdoc#116]
I am having difficulty putting together the information regarding Taxonomy and Front Matter in ordering my menu item by e.g. date or weight

I have the following layout. Where do I place the weigh/date information so that I can sort my release notes in reverse chronological order i.e. 1.5.2 is the first item

![MenuItemOrderingQuestion](https://user-images.githubusercontent.com/486172/117872058-0c1a1e00-b253-11eb-84d6-bdd9d3604d73.jpg)

**Comment by xoxys** [comment]
Please your GitHub Discussions for such topics. I'll transfer this issue.
