### ISSUE TITLE
Duplicate favicons?

### ISSUE THREAD

**Issue by KeisukeShima** [thegeeklab/hugo-geekdoc#125]
Hello. Thank you very much for making a great Hugo theme.
I tried to customize the favicon in this theme, but just copying and changing `favicons.html` didn't work. Then I checked with Chrome Devtool and noticed that the link to the icon in the head tag was declared twice.
Here is a link to the page where the link to the icon is listed.

https://github.com/thegeeklab/hugo-geekdoc/blob/main/layouts/partials/head/favicons.html#L1
https://github.com/thegeeklab/hugo-geekdoc/blob/main/layouts/partials/head/others.html#L1

**Comment by xoxys** [comment]
Thanks for reporting! Will be fixed in the next release.
