### ISSUE TITLE
Add option to disable navigation sidebar

### ISSUE THREAD

**Issue by xoxys** [thegeeklab/hugo-geekdoc#128]
I have a question about how to remove the left hand menu in certain pages

My API docs are in OpenAPI.

I have used `redo-cli bundle` to create HTML (and `sed` to add the front matter)

However the OpeAPI content is very wide (3 columns) and it would be very useful to switch off the left hand nav menu on this one page.

Is there some cleaver shortcode or front matter content I can use to switch this off please?

BTW, the issue is the same if you use Swagger

_Originally posted by @alecthegeek in https://github.com/thegeeklab/hugo-geekdoc/discussions/122_

**Comment by alecthegeek** [comment]
Tested. Works for me
