### ISSUE TITLE
Can you replace `Navigation` and `More` with variable?

### ISSUE THREAD

**Issue by septvean** [thegeeklab/hugo-geekdoc#13]
Hi, the file `layouts/partials/menu.html`, Can you replace `Navigation` and `More` with variable?

For example:

replace `Navigation`

```html
        {{ if .Site.Params.Navigation }}
            <h2>{{ .Site.Params.Navigation }}</h2>
        {{ else }}
            <h2>Navigation</h2>
        {{ end }}
```

replace `More`

```html
            {{ if .Site.Params.More }}
                <h2>{{ .Site.Params.More }}</h2>
            {{ else }}
                <h2>More</h2>
            {{ end }}
```

This may facilitate the localization.

**Comment by xoxys** [comment]
Thanks for your report. Right now, localization is not really supported. As there might be other hard coded strings and parameters are not the best option for localization this would need a bit more work :)

**Comment by xoxys** [comment]
Superseded by https://github.com/thegeeklab/hugo-geekdoc/issues/236
