### ISSUE TITLE
darkmode toggle button not showing

### ISSUE THREAD

**Issue by capsulecorplab** [thegeeklab/hugo-geekdoc#138]
I bumped the submodule for geekdoc to v0.12.0 on my hugo [site](https://303adastra.github.io/clockdriveos/) (hosted on GitHub Pages), but not see the darkmode toggle button

**Comment by capsulecorplab** [comment]
False alarm, I hadn't pushed my commits :facepalm:

**Comment by xoxys** [comment]
No worries glad to hear it works now.

**Comment by capsulecorplab** [comment]
I can't seem to get it working locally, but it at least works on GitHub Pages. Should that be expected?

**Comment by xoxys** [comment]
That would need more information/debugging. It should definetly work locally as well.

**Comment by xoxys** [comment]
If you could provide a reproducible example that I can check out locally I can take a look as well.
