### ISSUE TITLE
Search unicode not work

### ISSUE THREAD

**Issue by renyuntao** [thegeeklab/hugo-geekdoc#147]
Search unicode character in search bar not work

**Comment by xoxys** [comment]
Do you have an example?

**Comment by xoxys** [comment]
If you are talking about emojis, that seems to be an upstream issue https://github.com/nextapps-de/flexsearch/issues/166.

**Comment by renyuntao** [comment]
The following example search "申请" doesn't show any result:
![tmp](https://user-images.githubusercontent.com/11660067/121977207-06ff4000-cdb8-11eb-8084-df41d2f48af2.png)

**Comment by renyuntao** [comment]
Any suggestions?

**Comment by xoxys** [comment]
Still looks like an upstream related config issue. https://github.com/nextapps-de/flexsearch/issues/51#issuecomment-630094955

**Comment by xoxys** [comment]
You can play with the `geekdocSearchConfig` variable  in https://github.com/thegeeklab/hugo-geekdoc/blob/main/assets/js/search.js#L24 to pass in a custom search config or temp. overwrite the entire file to test other search configurations.

I have not tested it that much on my own right now.

**Comment by xoxys** [comment]
See https://github.com/thegeeklab/hugo-geekdoc/issues/147#issuecomment-863005530
