### ISSUE TITLE
IMG  shortcode not working

### ISSUE THREAD

**Issue by MikeyC3040** [thegeeklab/hugo-geekdoc#166]
Using the IMG shortcode produces no html. I have tried copying and pasting the example code and resources for a direct test.
I have had no issues with any other shortcodes such as columns.
Geekdoc version: 0.15.0
Hugo version: 0.85.0

Edit: So my copy and paste was not as direct as I thought. Turns out it was because I had my resources in a sub folder. Once they are no longer in the sub folder it works

**Comment by xoxys** [comment]
Glad to hear you got it to work. This behavior is due to Hugos content structure. By default, the theme uses https://gohugo.io/content-management/page-bundles/#branch-bundles to auto-generat the navigation tree, see http://localhost:1313/usage/menus/#file-tree-menu

But you can choose whatever content structure you like while using the http://localhost:1313/usage/menus/#file-tree-menu. This way, you would be able to create a content structure like this:

```
exampleSite/content/test/
├── img
│   └── forest-1.jpg
└── index.md
```

**index.md**
```
---
resources:
  - name: forest-1
    src: "img/forest-1.jpg"
    title: Forest (1)
    params:
      credits: "[Jay Mantri](https://unsplash.com/@jaymantri) on [Unsplash](https://unsplash.com/s/photos/forest)"
---

Foo

**Demo:**

{{< img name="forest-1" lazy=false >}}
```

**Result**

![grafik](https://user-images.githubusercontent.com/3391958/126028464-b319f132-0826-4ecc-878a-e6f4c7df6b7d.png)

Keep in mind, you **have** to use the file-tree menu and create your site navigation manually with a data file.

**Comment by xoxys** [comment]
I'm going to close this one. Feel free to open a new issue if you find another bug.

**Comment by Allaman** [comment]
Hello, I still am not getting to work and I am stucked for hours :( 
Do you see my mistake?

![image](https://user-images.githubusercontent.com/12184268/135185806-d5b8b6d8-29d8-44be-aac7-9fc744dca0ba.png)
![image](https://user-images.githubusercontent.com/12184268/135185880-d591052b-196a-4aed-a368-109adfd33b61.png)
![image](https://user-images.githubusercontent.com/12184268/135185929-9c5238dc-297a-431e-8eba-f0276de6df10.png)

**Comment by xoxys** [comment]
Hi, as mentioned in my last comment of this issue, it's all about Hugos content structure :) Take a look at https://gohugo.io/content-management/page-resources/:

> Page resources are only accessible from page bundles, those directories with index.md or _index.md files at their root. Page resources are **only available to the page with which they are bundled**.

In your example, your page bundle called `linux` (initialized as a bundle by the `_index.md` file) has technically three pages resource; two pages and an image. The important thing to understand is, the resources can only be accessed by the `_index-md` or `index.md` page and **not** by any other page in this bundle, e.g. `filesystem.md` as this page is a page resource of the bundle on its own. While there are some workarounds to access page resources from other pages in a bundle as well, I have not found a good way to dynamically handle it in the `img` shortcode.

That being said, there is another way how you could achieve the structure you want. For every page inside a bundle that should include images, create a nested bundle:

```Shell
linux/
├── filesystem
│   ├── forest-1.jpg
│   └── _index.md
├── _index.md
└── nixos.md
```

PS: Next time, please don't use closed issues. Create new one or use GitHub [Discussions](https://github.com/thegeeklab/hugo-geekdoc/discussions)

**Comment by Allaman** [comment]
Thank you very much for clarification. That drove me crazy. Your explanation is imho way better than the one in the Hugo docs
