### ISSUE TITLE
Tables do not scroll on mobile

### ISSUE THREAD

**Issue by ListenerJubatus** [thegeeklab/hugo-geekdoc#176]
A [page](https://outfox.wiki/dev/songs/bms-pms-dtx-support/) on our Geekdoc-based site has a very wide table, but we've noticed that you cannot scroll through tables when in a mobile view.

Is there a way that this could be fixed either with a CSS override, or an upstream change to the stylesheets?

**Comment by xoxys** [comment]
Thanks for your report! The fix will be shipped with the next release.
