### ISSUE TITLE
"Edit this page" link inserts html url encoded backslashes instead of forward slashes

### ISSUE THREAD

**Issue by brendan-mccoy** [thegeeklab/hugo-geekdoc#185]
hugo v0.87.0-B0C541E4+extended windows/amd64 BuildDate=2021-08-03T10:57:28Z VendorInfo=gohugoio

When the theme builds the "Edit this page" URLs, some reason instead of forward slashes, it inserts HTML url encoded backlashes as "%5c" after the geekdocEditPath string in the params, e.g., https://github.com/thegeeklab/hugo-geekdoc/edit/main/exampleSite/content/usage%5cconfiguration.md.

This leads to 404s on both github and gitlab repos. I'm not sure why this happens on my own site and not on the demo site at https://geekdocs.de/.

My only guess is it is a Windows Hugo specific issue but I don't see why that would be the case.

**Comment by brendan-mccoy** [comment]
I should have added, this is using v0.16.6.

I will try with the release that was just done.

**Comment by brendan-mccoy** [comment]
Based on https://github.com/gohugoio/hugo/issues/5515 I think this is not an issue with the theme but with Hugo on Windows.

**Comment by xoxys** [comment]
Closed by https://github.com/thegeeklab/hugo-geekdoc/pull/186
