### ISSUE TITLE
In <head> RSS link breaks if .Site.Title has quotes (")

### ISSUE THREAD

**Issue by danielfdickinson** [thegeeklab/hugo-geekdoc#201]
In the following there is an error.

https://github.com/thegeeklab/hugo-geekdoc/blob/f1a713d59a54c7c934eb931f9238c19e7beba5e4/layouts/partials/head/others.html#L19

It breaks[1] when ``$.Site.Title`` contains quotes ("). The solution is to replace that line with:

```html
    {{ printf `<link rel="%s" type="%s" href="%s" title="%s" />` .Rel .MediaType.Type .Permalink ($.Site.Title | htmlEscape ) | safeHTML }}
```

[1] Meaning the ``title`` attribute ends up looking like:

```
title="Some "quoted name""
```
if ``.Site.Title`` is ``Some "quoted name"``.

This obviously won't parse as desired.

**Comment by xoxys** [comment]
Thanks for your report. RSS/Feeds at all is not supported for this theme, so I'm going to remove the block completely for now.
