### ISSUE TITLE
Add parameter "favicon" to change the website icon

### ISSUE THREAD

**Issue by shdennlin** [thegeeklab/hugo-geekdoc#206]
Can add a parameter "favicon" to change the website icon in "config.yaml" ?

**Comment by xoxys** [comment]
Thanks for your request. Favicons are complicated these days, there are a lot of different formats and platforms to support, therefor a theme parameter is not the best way. If you want to customize, you just need to [overwrite](https://gohugo.io/templates/partials/#partial-template-lookup-order) [this partial](https://github.com/thegeeklab/hugo-geekdoc/blob/main/layouts/partials/head/favicons.html) and place the required files in the static folder of your project.

**Comment by shdennlin** [comment]
Thanks for your answer, I'll try it.
