### ISSUE TITLE
Theme with custom.css is not rendering properly on windows

### ISSUE THREAD

**Issue by OrlinVasilev** [thegeeklab/hugo-geekdoc#222]
Hi there, thanks for the great theme!

When rendering on Mac it takes into account the custom.css
but when I run the same code on Windows the theme is not with my colours

Any idea?

**Comment by xoxys** [comment]
Do you get any feedback so far?

**Comment by OrlinVasilev** [comment]
some search a bit show that hugo works differently with the caches on Windows! So --ignoreCache and --noHTTPCache solved the issue. Thank you!
