### ISSUE TITLE
Copy button for code fences

### ISSUE THREAD

**Issue by matkoch** [thegeeklab/hugo-geekdoc#226]
First of all: great theme! I'm going to convert my current documentation website to this.

Now what I'm missing, but definitely not a blocker, is a button to copy code, similar to the following:

<img width="664" alt="image" src="https://user-images.githubusercontent.com/5005566/140235778-46cd43d1-8fa0-42e6-a248-0c20cf1583c0.png">

Would be great to get this, and if I can be of any help, please let me know.

**Comment by matkoch** [comment]
thanks a lot :)

**Comment by xoxys** [comment]
Hope you enjoy it :) please test it and report bugs.
