### ISSUE TITLE
custom css relocation

### ISSUE THREAD

**Issue by yqlbu** [thegeeklab/hugo-geekdoc#231]
Hi,

I noticed that the default `custom.css` file is set to be located in `static/custom.css`. I wonder if there is any way I can load my custom css file from `static/css/custom.css`?

**Comment by xoxys** [comment]
Hi,

yes you can overwrite https://github.com/thegeeklab/hugo-geekdoc/blob/main/layouts/partials/head/others.html#L15-L16 or add your own CSS file to e.g. https://github.com/thegeeklab/hugo-geekdoc/blob/main/layouts/partials/head/custom.html
