### ISSUE TITLE
Multilingual Support (Language Selector)

### ISSUE THREAD

**Issue by mbkma** [thegeeklab/hugo-geekdoc#236]
Hi there! First of all thanks a lot for your hard work and this awesome theme. I used it to make the MATE Wiki: https://wiki.mate-desktop.org/. Recently there was the need to add some translation to the website, but while enabling [Multilingual Mode](https://gohugo.io/content-management/multilingual/) in Hugo is relatively simple, I could not find a simple way to add a language selector to this theme. Is it possible to add a language selector like in this theme (https://learn.netlify.app/en/)?
![Screenshot at 2021-11-08 21-57-12](https://user-images.githubusercontent.com/39454100/140817082-bcdaf2de-c73e-46a9-b054-db692938598a.png)
Maybe you would need to add something like:
```
{{ if .IsTranslated }}
	<nav class="LangNav">
	{{ range .Translations }}
		<a href="{{ .Permalink }}">{{ .Language.LanguageName }}</a>
	{{ end}}
	</nav>
{{ end }}
```
(found this at https://www.regisphilibert.com/blog/2018/08/hugo-multilingual-part-1-managing-content-translation/)

**Comment by xoxys** [comment]
Hi, sure possible :) and we got multiple requests for multilanguage support, but I have not started to work on it till now.

**Comment by mbkma** [comment]
awesome, thanks :+1:

**Comment by xoxys** [comment]
Finally, even if it took a little longer than expected. Feedback and issue reporting would be very welcome :)
