### ISSUE TITLE
Make it possible to collapse navigation bar items which have child items

### ISSUE THREAD

**Issue by bazsodombiandras** [thegeeklab/hugo-geekdoc#243]
It would be nice to have to possibility to collapse/expand the navigation bar items which have child items under them. This could be controlled by a config option.

Consider the following example:
```
Navigation
Posts
    Reports
        Mary
            2021 November
            2021 October
            2021 September
            ...
        Joseph
            2021 November
            2021 October
            2021 September
            ...```

As time goes by and a report is published each month both for Mary and Joseph, Mary's list grows very large and you have to scroll down a lot to get to Joseph's reports. Collapsing/expanding the "Mary" node elegantly solves this problem.

**Comment by xoxys** [comment]
That's already possible. You can control this for each individual section using [`geekdocCollapseSection`](https://geekdocs.de/usage/configuration/#page-configuration) or globally using `GeekdocCollapseAllSections` on your projects' config file.

**Comment by xoxys** [comment]
There is also a demo section on the docs page if you want to see it in action:

![image](https://user-images.githubusercontent.com/3391958/142659278-4a2cd948-cf11-4ee6-88de-cf10e06b18de.png)

**Comment by bazsodombiandras** [comment]
That's awesome! how can I add geekdocCollapseSection to just one section, not from the global config.toml?

**Comment by xoxys** [comment]
As you would do with every page config 🙂 add it to the front matter of the section. See https://raw.githubusercontent.com/thegeeklab/hugo-geekdoc/main/exampleSite/content/collapse/level-2/_index.md

**Comment by bazsodombiandras** [comment]
Wow, didn't know it's possible to do configs per section. Thanks!

Is there any way I could donate a small symbolic sum (like 5 euros) to you to buy you a coffee for all the great work that you do with this theme?

**Comment by bazsodombiandras** [comment]
The collapsing works like magic per level, however if I make some sections collapsible, the leaf levels (lowest levels) start as collapsed by default. Is there any way to make them collapsible but have them be expanded by default?

**Comment by bazsodombiandras** [comment]
Important things have been clarified. Thank you very much for your help!

**Comment by xoxys** [comment]
> Is there any way I could donate a small symbolic sum (like 5 euros) to you to buy you a coffee for all the great work that you do with this theme?

Right now, I don't have a way to make donations. But your kind words are very welcome :) If you want to support our work, please keep reporting issues, star this repo and tell others about it. That helps a lot.

**Comment by xoxys** [comment]
> The collapsing works like magic per level, however if I make some sections collapsible, the leaf levels (lowest levels) start as collapsed by default. Is there any way to make them collapsible but have them be expanded by default?

Right now, that's not possible. I would need to take a look if we could support it somehow.

**Comment by bazsodombiandras** [comment]
> > The collapsing works like magic per level, however if I make some sections collapsible, the leaf levels (lowest levels) start as collapsed by default. Is there any way to make them collapsible but have them be expanded by default?
> 
> Right now, that's not possible. I would need to take a look if we could support it somehow.

Not abig deal, it's quite OK as it is. Thank you!

**Comment by bazsodombiandras** [comment]
> > Is there any way I could donate a small symbolic sum (like 5 euros) to you to buy you a coffee for all the great work that you do with this theme?
> 
> Right now, I don't have a way to make donations. But your kind words are very welcome :) If you want to support our work, please keep reporting issues, star this repo and tell others about it. That helps a lot.

Will do! Geekdoc is by far the nicest Hugo theme I've found for my personal needs.
