### ISSUE TITLE
Add option to customize footer text

### ISSUE THREAD

**Issue by jcrd** [thegeeklab/hugo-geekdoc#244]
An option to customize the left portion of the footer text would be useful.
I disable HTML minification per #81 to avoid the issue with this text, but unminified files are ~30% larger.
Custom text could bypass this issue and allow use of minification.

**Comment by xoxys** [comment]
Sorry, this will not happen. I have outlined my opinion about the hugo minify option pretty clear in the linked issue, stripping whitespaces within a span element is just bullshit. If you really want to use the hugo minifier you are on your own:

- try to play with the options and e.g. [keep whitespaces](https://gohugo.io/getting-started/configuration/#configure-minify)
- use a better working minifier we use [js-beautify](https://github.com/thegeeklab/hugo-geekdoc/blob/main/.drone.yml#L205) for example
- you can overwrite any file you want on your own utilizing Hugo's [lookup order](https://gohugo.io/templates/lookup-order/)
