### ISSUE TITLE
data/menu/main.yaml

### ISSUE THREAD

**Issue by denispeyrusaubes** [thegeeklab/hugo-geekdoc#26]
Your exampleSite uses menu-filetree's partial.
Is there an example of using "menu-bundle" with a `data/menu/main.yaml` somewhere ?

I have tried to use same syntax than `data/menu/more.yaml` returns a `[en] REF_NOT_FOUND: Ref "/docs/Exercice2.1.md" from page "k9s.md": page not found` 

Thank you !

**Comment by xoxys** [comment]
Sadly this is not really documented so far, but you can find a working setup here https://github.com/thegeeklab/ansible-later/tree/master/docs. You have to enable it in the config as well https://github.com/thegeeklab/ansible-later/blob/master/docs/config.yaml#L21

**Comment by xoxys** [comment]
@denispeyrusaubes Were you able to get it working?
