### ISSUE TITLE
Is there a way to show tags in posts?

### ISSUE THREAD

**Issue by tru2dagame** [thegeeklab/hugo-geekdoc#260]
Thanks for the Geekdoc theme. Really like the doc style a lot.
Is there a way to always show tags in post like Geekblog?

<img width="286" alt="image" src="https://user-images.githubusercontent.com/1673006/148283497-eb46fe7d-5b37-4dae-80aa-b0cc9218dfcb.png">

**Comment by xoxys** [comment]
Thanks. No, that's not possible out of the box.

**Comment by xoxys** [comment]
I was wrong, we had implemented this already, see https://geekdocs.de/posts/ and https://raw.githubusercontent.com/thegeeklab/hugo-geekdoc/main/exampleSite/content/posts/hello_geekdoc.md

**Comment by xoxys** [comment]
The linked PR unifies the post metadata and shows it on the list view as well as on the single page view. Hope this will fix the issue for you finally.

**Comment by tru2dagame** [comment]
Thanks for the update. I really appreciate it.
