### ISSUE TITLE
Does mermaid work in included file?

### ISSUE THREAD

**Issue by igel2000** [thegeeklab/hugo-geekdoc#273]
Thanks for the Geekdoc theme.
I am trying to use mermaid shortcodes in an included file, but it doesn't work. Other shortcodes work.
Is this a bug or a feature?

**Comment by xoxys** [comment]
We use the latest release on https://geekdocs.de/shortcodes/mermaid/ as well and as you can see mermaid works. Have you followed the setup guide? What version of the theme do you use?

**Comment by xoxys** [comment]
Sorry, I haven't read your issue carefully enough. You try to use it with an included, I'm not sure if that was every working but I can take a look later.

**Comment by igel2000** [comment]
Sorry, I was wrong, other shortcode do not work either in include.

**Comment by xoxys** [comment]
How have you done the include? Can you create a public repo to reproduce the issue? For me, this works as expected:

![image](https://user-images.githubusercontent.com/3391958/148783643-4fcef399-15e8-4ff7-98f2-0d15c6220568.png)

You have to use the page include as described in https://geekdocs.de/shortcodes/includes/#pages

**Comment by xoxys** [comment]
I found the issue, you have to specify the include type like this `{{< include file="/_includes/included.md" type="page" >}}`. I'll fix the documentation. Thanks for reporting and the test repo.

**Comment by igel2000** [comment]
Thank you! It works for me.
