### ISSUE TITLE
Code inside hint illegible in Dark Mode

### ISSUE THREAD

**Issue by Seanny123** [thegeeklab/hugo-geekdoc#278]
Code inside of a hint fails to render visibly when viewing the document in Dark Mode.

## Example

Given the following markdown:
```
## Using `code`

{{< hint danger >}}
Using `code` while dark.
{{< /hint >}}
```

The rendering is illegible while viewing it in dark mode:
![image](https://user-images.githubusercontent.com/1918825/149031662-ccbcc6eb-9db6-4238-a6c0-b5c82aaaa0e7.png)

But legible in light mode:
![image](https://user-images.githubusercontent.com/1918825/149031726-5b04deb0-87e5-4b74-a761-4648df74d3cd.png)

## Possible cause

I think the hint styling over-rides the body font, which also overrides the code's font?

Specifically, in `src/sass/_shortcodes.scss`:
```
// {{< hint >}}
.gdoc-hint {
  @each $name, $color in $hint-colors {
    &.#{$name} {
      border-left-color: $color;
      background-color: scale-color($color, $lightness: 95%, $saturation: -30%);
      color: $body-font-color;
    }
  }

  .gdoc-page__anchor {
    display: none;
  }
}
```

**Comment by xoxys** [comment]
Thanks for your report. Right now, I'm not able to reproduce it:

![image](https://user-images.githubusercontent.com/3391958/149099352-4e71254a-5110-4157-a9a2-beb7aa2335bd.png)

Have you customized the theme or just use it as it is? What version do you use?

**Comment by xoxys** [comment]
IIRC we have fixed this in https://github.com/thegeeklab/hugo-geekdoc/pull/159 already, so I guess you are running an older version and would have to upgrade the theme.

**Comment by Seanny123** [comment]
I can't believe I forgot to check what version I was using. I'm on 0.13.5. My apologies.

**Comment by xoxys** [comment]
Nah no worries 🙂
