### ISSUE TITLE
Subfolder deployment creates wrong link(s)

### ISSUE THREAD

**Issue by SeBaBu** [thegeeklab/hugo-geekdoc#286]
Hey, I have only noticed this when using Mermaid, so there might be more things not linking correctly.
With
`baseURL = "https://domain.tld/wiki"`
and a deployment via
`hugo --cleanDestinationDir --destination <path to subfolder>`
the file `273.chunk.min.js`is linked without the `/wiki/` part. It can be repaired by manually adding it inside mermaid.bundle.min.js:
`... {return"wiki/js/"+t+".chunk.min.js"}... `

Strangely, this does not happen when using:  `hugo server -D`

**Comment by xoxys** [comment]
Hi, thanks for your report. Even if it is strange that `hugo` and `hugo server` end up with different results (I was not able to reproduce this part) I can confirm that we had introduced some issues related to subfolder deployments as part of the [switch to webpack](https://github.com/thegeeklab/hugo-geekdoc/pull/258) as build tool. 

I'm currently working on a fix already, but you might want to read https://geekdocs.de/usage/getting-started/#subdirectories as well. There are some other pitfalls and corner cases when it comes to subfolder deployments, and we still recommend avoiding it whenever possible.
