### ISSUE TITLE
Bad layout with code highlight

### ISSUE THREAD

**Issue by tgarlot** [thegeeklab/hugo-geekdoc#30]
First, congratulations for the theme, really great and well documented !!

I'm trying to move my site to this theme and I've an issue with code hightligh just using the example:

` ```Shell
echo "Hello world"
``` `

is not displayed nicely but like this:

![Screenshot 2020-12-01 at 06 34 30](https://user-images.githubusercontent.com/4187639/100701142-51cae480-339f-11eb-9741-93ab3c5de198.png)

For "some reasons", the generated hteml is adding some inline CSS 

`<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-Shell" data-lang="Shell"><span style="color:#75715e"># some code</span>
echo <span style="color:#e6db74">"Hello world"</span>
</code></pre></div>`

Not sure if the issue is with the theme or with Hugo highlight... Perhaps also a "navigator issue"...

Thanks in advance

**Comment by tgarlot** [comment]
Still investigating, most probably something related to Chroma/Highlight and not with the theme itself...

**Comment by tgarlot** [comment]
Got it :-) Not related to yout theme at all...

I put `pygmentsUseClasses=true` at the wrong place in config.toml (at the bottom and not with other "one-liner" configuration. I need to read and learn a bit more about toml :-)

Sorry for the wrong issue

**Comment by xoxys** [comment]
No worries glad that you found a solution 🙂
