### ISSUE TITLE
Light/Dark mode flashes

### ISSUE THREAD

**Issue by mbkma** [thegeeklab/hugo-geekdoc#304]
Hi,
I get a really strange behavior with our site https://wiki.mate-desktop.org/:
When on dark mode, during loading the web page switches to light mode until the site finished loading. And the color mode switcher disappears for a short while. To illustrate I made a gif:

![Peek 2022-01-30 20-34](https://user-images.githubusercontent.com/39454100/151714880-b30a4b0d-10ed-436b-95b1-aaed1b48dea8.gif)

The strange thing is that it does not happen with the deployment at https://wiki.mate-desktop.dev/ which we use to preview PRs on the wiki (but both deployments should be identical atm).

**Comment by xoxys** [comment]
Hi, to be honest, I have no idea. I have not encountered this problem in any of my own deployments yet. I was also not able to reproduce it with a local build of your repo even with a browser simulated network throttling :( 

Maybe there are some old artifacts left in your gh-pages branch that somehow causes some strange side effects?

**Comment by mbkma** [comment]
ok, thanks. I did not expect that your theme was causing the issue anyway, just wanted to make sure.

**Comment by xoxys** [comment]
You are always welcome and if you find something that we can improve we would be happy to do so. I would also like to hear if you were able to resolve it.
