### ISSUE TITLE
Error building site: failed to render pages: Latest release on Windows

### ISSUE THREAD

**Issue by andikrueger** [thegeeklab/hugo-geekdoc#317]
I downloaded the latest release package and placed it under themes/hugo-geekdoc.

when running `hugo server -D` I do get the following error message:

```powershell
> hugo server -D
Start building sites … 
hugo v0.92.1-85E2E862+extended windows/amd64 BuildDate=2022-01-27T11:44:41Z VendorInfo=gohugoio
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:15:7: executing "_default/single.html" at <partial "head/schema" .>: error calling partial: "C:\DEV\Governance-Framework\themes\hugo-geekdoc\layouts\partials\head\schema.html:61:44": execute of template failed: template: partials/head/schema.html:61:44: executing "partials/head/schema.html" 
at <.Params.tags>: range can't iterate over
Built in 825 ms
```

Other install options like cloning the repo and building it locally did fail too. The documentation is no longer up to date with the new `npm run build script` which still fails on my windows system.

**Comment by andikrueger** [comment]
I found a workaround. I had a file with the name `_index.md` in one of the folders. Renaming did the trick and I'm able to run the server again.

**Comment by andikrueger** [comment]
No workaround found. I did some changes and am still seeing the error.

**Comment by xoxys** [comment]
Please provide more details how to reproduce the issue or create a minimal reproducible repository.

**Comment by xoxys** [comment]
> The documentation is no longer up to date with the new `npm run build script`

Fixed by: https://github.com/thegeeklab/hugo-geekdoc/pull/318

>  which still fails on my windows system
We would need more details here as well... We tried to use platform independed tools, there might be room for improvements.

**Comment by andikrueger** [comment]
I'm totally new to hugo and the templates. Will try to build up a demo on the issue with the build and collect some data on the build of the repo. My first demo to reproduce the issue works like a charm. Let me see, if I can figure out, what part of my current structure breaks the template.

**Comment by andikrueger** [comment]
I will create a new issue for my build issues and will update this one with more information about the error above.

**Comment by andikrueger** [comment]
Looks like I found the root cause of the issue within my md files. Please find attached an example md file and place this in the content folder.

[test.md](https://github.com/thegeeklab/hugo-geekdoc/files/8002368/test.md)


```markdown
---
title: Manage settings
description: settings are critical for the environment.
date: '2022-02-02T13:56:43.027Z'
preview: ''
draft: ''
tags: ''
categories: ''
lastmod: '2022-02-04T10:43:35.704Z'
keywords:
    - Microsoft
---
```

**Comment by xoxys** [comment]
Yeah, that will of course not work. Where did you get this from? Have you created it by hand? `tags:` is a list. If you set it to a (an empty) string, this will break the iteration. Just remove it from the front matter if you don't use it.

**Comment by andikrueger** [comment]
Good catch. I used the[ vscode frontmatter extension](https://github.com/estruyf/vscode-front-matter) to add tags and did remove all of them. Will raise this issue there too.

Any chance to catch the empty string within the template?

**Comment by xoxys** [comment]
Yes will look into a possible hardening later.
