### ISSUE TITLE
Collapse does not work

### ISSUE THREAD

**Issue by mahmoudozil** [thegeeklab/hugo-geekdoc#33]
i downloaded the latest version .. put it in a folder main/themes/geekdoc
i started my main project with hugo server -D
added the geekdocCollapseSection: true
but nothing appears

**Comment by xoxys** [comment]
Hi, needs some more input. What browser do you use? `hugo server -D` runs without errors? What exactly means  "nothing appears"? Do you have content added to your site? How does your content look like? `geekdocCollapseSection` needs to be added to your page front matter.

**Comment by xoxys** [comment]
You can find an example folder structure here https://github.com/thegeeklab/hugo-geekdoc/tree/master/exampleSite/content/collapse. Thats how the documentation page is deployed https://geekdocs.de/ where you can see collapse in action.

**Comment by mahmoudozil** [comment]
I copied the content towards my application but the collapse does not work .. on the other hand geekdocHidden works fine

![image](https://user-images.githubusercontent.com/26530104/101387657-0a70b680-38bf-11eb-86dc-d64bf9c26300.png)

**Comment by mahmoudozil** [comment]
the arrows do not appear near the collapse menu
![Capture](https://user-images.githubusercontent.com/26530104/101388153-d944b600-38bf-11eb-82d7-ce10328448ab.PNG)

**Comment by xoxys** [comment]
What browser do you use?

**Comment by xoxys** [comment]
I'm not able to reproduce it:

```
hugo new site demosite
cd demosite
mkdir -p themes/hugo-geekdoc/
curl -L https://github.com/thegeeklab/hugo-geekdoc/releases/latest/download/hugo-geekdoc.tar.gz | tar -xz -C themes/hugo-geekdoc/ --strip-components=1
vi config.toml # add the content from the getting-started guide
cp -r  /tmp/hugo-geekdoc/exampleSite/content/collapse/ content/
hugo server -D
```

![image](https://user-images.githubusercontent.com/3391958/101400993-fbdfca80-38d1-11eb-8afe-ff6230a06a94.png)

**Comment by mahmoudozil** [comment]
thank you it works now
