### ISSUE TITLE
Search doesn't work with static generation without use of web server

### ISSUE THREAD

**Issue by nicolofrison** [thegeeklab/hugo-geekdoc#34]
Hi,
I was trying to use this theme as static html's without a web server and all works fine except the search function. 
I used the example site and when the search box is clicked, the browser try to load 2 js, but it doesn't work because the path is not relative to the html file. 
I tried to put a fixed value in order to see how does it works, and I saw that also the results of the research have the path problem. 
Are possible to make the search works also for static html without web server?

**Comment by xoxys** [comment]
Thanks for your request. I'm sorry but this is not a supported scenario. Can you please explain a bit more in which situation this use-case is required?

**Comment by nicolofrison** [comment]
I would like to generate my documentation from markdown files to html files, and opening them directly without the use of a web server

**Comment by xoxys** [comment]
I guess you are using `relativeURLs = true`  in your config.toml right? Looks like this is an upstream issue https://github.com/gohugoio/hugo/issues/2744. I can't see a way to easily fix this in the theme itself and I don't want to add and maintain a quite complex workaround.

**Comment by xoxys** [comment]
I'm open to review pull requests but as this is an upstream issue in Hugo and there is AFAIK no simple way to fix it in the theme itself I'm going to close this issue.
