### ISSUE TITLE
TOC Sidebar

### ISSUE THREAD

**Issue by morph027** [thegeeklab/hugo-geekdoc#355]
First of all, thanks for the wonderful theme! I really appreciate your work.

Not sure if this has been asked already, search did not yield any results for me.

Is it possible to add a new sidebar on the right which includes the TOC of the current page (example: https://hugo-book-demo.netlify.app/) ?

**Comment by xoxys** [comment]
Hi, thanks for your request. That's not possible, sorry. I don't like the approach of a three-column design, and removing the ToC sidebar was one of the reasons why I forked the [hugo-book](https://github.com/alex-shpak/hugo-book) theme.

As this was a basic design decision, I'm closing this issue as won't fix and hope you understand that.

**Comment by morph027** [comment]
Sure, won't question this ;) Thanks for your quick response anyways!
