### ISSUE TITLE
General width

### ISSUE THREAD

**Issue by morph027** [thegeeklab/hugo-geekdoc#356]
Can we easily increase the page width using variables or layout overrides?

I've tried changing `gdoc-page`, which does grow, but `gdoc-nav` stays in place and should move to the left.

**Comment by xoxys** [comment]
That's also not possible, and I don't found a way to handle it properly.

**Comment by xoxys** [comment]
What you would need to override is the `max-width` of `.container`. This might solve your issue :)

**Comment by morph027** [comment]
Thanks, will have a look later.

**Comment by morph027** [comment]
Great, works well and looks good when set to 90% ;)

Is there any chance of adding an override from outside the theme or do i modify to modify `src/sass/_defaults.scss` and then run `npm run build` each time i'm building the site (preferably within CI)...

The reason i'm switching over is that the last theme i was using (Learn) has been modified so much already, that it's basically a new theme, which is hard to maintain and i prefer to stick as close as possible to the upstream repo.

Anyways, thank you for the hint :+1:

**Comment by xoxys** [comment]
Yes of course, you can just override it using a `static/custom.css` file within your project directory as described in https://geekdocs.de/features/theming/.

**Comment by morph027** [comment]
Awesome and thanks!
