### ISSUE TITLE
Improvement for search

### ISSUE THREAD

**Issue by LukasHirt** [thegeeklab/hugo-geekdoc#37]
Hi, I was thinking about an improvement to the search. When we're searching for a term which is used in different parts of docs, we currently do not recognise where is it coming from. It can become really hard to navigate then - see following example.

![Screenshot 2020-12-20 at 16 10 32](https://user-images.githubusercontent.com/25989331/102716713-e7da9680-42dd-11eb-8f68-c7bc26f17930.png)

I hoped we could get some improvement like this:

![Screenshot 2020-12-20 at 16 11 05](https://user-images.githubusercontent.com/25989331/102716725-fa54d000-42dd-11eb-8d18-9c0a67791101.png)

This would also turn the search results into a dropdown which I think could be a nice addition as well. It would not push the content of navigation then creating this "jump" and could be dismissed by simply clicking on the screen instead of having to delete the search query.

Let me pls know @xoxys if this is something you'd be interested in bringing to this already awesome theme. I'd be happy to even take care of coding this.

**Comment by xoxys** [comment]
Hi it would be really awesome to improve the search. Were you thinking about a compeltey new search engine or just improving the current implementation in the theme? Right now the theme works with flexsearch.

**Comment by LukasHirt** [comment]
If there are no issues with flexsearch and I'd be able to achieve this with it, I wouldn't see a reason to use a new one. Unless you were already considering to switch?

**Comment by xoxys** [comment]
No strong opinion :) but I would like to keep using an existing framework instead of a full reimplementation.
