### ISSUE TITLE
Asciidoctor: admonitions not rendered properly

### ISSUE THREAD

**Issue by d1nuc0m** [thegeeklab/hugo-geekdoc#378]
When using geekdoc with Hugo and Asciidoctor, the [admonitions](https://docs.asciidoctor.org/asciidoc/latest/blocks/admonitions/) are not rendered properly. Icons are not displayed, what is rendered is a text block with the admonition name written vertically. See the attached minimal example for more information [example-Admonitions.zip](https://github.com/thegeeklab/hugo-geekdoc/files/8507025/example-Admonitions.zip).

Info:
- Asciidoctor 2.0.17
- Geekdoc v0.28.0 (also tested with v0.18.0)
- Hugo v0.96.0

**Comment by xoxys** [comment]
Thanks for the report. Should be fixed in the main branch already, Ill tag a new release later.

**Comment by xoxys** [comment]
Admonitions look like the Hugo `hint` short code we have already to keep it consistent. As we don't support icons for the hint short code (yet) proper icon handling for the Asciidoc admonitions is also missing. 

![image](https://user-images.githubusercontent.com/3391958/163861930-241e953c-b8b9-453f-9f59-ec251c795ba5.png)

**Comment by d1nuc0m** [comment]
@xoxys I've downloaded master's zip at commit b104d6a and extracted it in the example I sent before.
Not only the admonitions aren't working, but the icons sizes are totally wrong (see attachment here  [example-2.zip](https://github.com/thegeeklab/hugo-geekdoc/files/8507745/example-2.zip)).
I hope I just did something wrong while testing.

About consistency, I think that users wouldn't be surprised if Hugo's shortcodes and Asciidoctor's blocks behave differently, as they're part of two different softwares, but what matters is that it works

**Comment by xoxys** [comment]
You can not just clone the repo checkout a commit or branch. As described in the [docs](https://geekdocs.de/usage/getting-started/#option-2-clone-the-github-repository), you have to build it (or wait for the release). I have merged the state shown in the screenshot now.

**Comment by d1nuc0m** [comment]
> You can not just clone the repo and checkout a commit or branch. As described in the [docs](https://geekdocs.de/usage/getting-started/#option-2-clone-the-github-repository), you have to build it (or wait for the release). I have merged the state shown in the screenshot now.

Oh ok, thanks, I missed that part... I'll wait
