### ISSUE TITLE
Icons for Hugo's hint and Asciidoc's admonitions

### ISSUE THREAD

**Issue by d1nuc0m** [thegeeklab/hugo-geekdoc#381]
As of #378 , icons for hint shortcode and admonitions are not supported yet (more as an information for other users than a reminder for the dev)

**Comment by xoxys** [comment]
Current approach with icons

![image](https://user-images.githubusercontent.com/3391958/164324779-7f0435b9-a47f-490c-a26a-bd038e974cbc.png)

... and the default text labels:

![image](https://user-images.githubusercontent.com/3391958/164324652-461f86ad-c065-4c47-984c-206ebee208f5.png)

Would be happy to get some feedback.

**Comment by d1nuc0m** [comment]
For consistency between Geekdoc and Asciidoc, I'd suggest something like this.
The table is ordered by "message importance" as defined in Asciidoc, where Warning means "danger, harm, or consequences that exist" (so it should be equivalent to danger Hint) and Caution means "act carefully" (so it is a warning)

| **Asciidoc** | **Geekdoc** | Icon                     | Color  |
|--------------|-------------|--------------------------|--------|
| NOTE         | Info        | Circled i                | Blue   |
| TIP          | Ok          | Tick or lamp             | Green  |
| IMPORTANT    | /           | Circled exclamation mark | Yellow |
| CAUTION      | Warning     | Crossed signal           | Violet |
| WARNING      | Danger      | Fire                     | Red    |

**Comment by d1nuc0m** [comment]
@xoxys  By the way, another idea: what about an "Important" hint shortcode, equivalent to Asciidoc's? As above, circled exclamation mark as icon and yellow as color

**Comment by xoxys** [comment]
> what about an "Important" hint shortcode

Agree and that works already, just need to be added to the docs and the example page.

**Comment by xoxys** [comment]
Thanks for your feedback. Added some adjustments.

## Admonitons
![image](https://user-images.githubusercontent.com/3391958/164780203-5cf7a859-8e25-410b-83cf-4d1cc0b6ab59.png)


## Hints
![image](https://user-images.githubusercontent.com/3391958/164780447-48e984d0-8d0d-497a-86c3-8a10a8870932.png)

**Comment by d1nuc0m** [comment]
> Thanks for your feedback. Added some adjustments.
Thank you for the great work, it looks very nice.
Guess it's time for a new release?

**Comment by xoxys** [comment]
>  Guess it's time for a new release?

Currently working on the missing icon handling for the hint short code :)

**Comment by xoxys** [comment]
Hint customizations:

![image](https://user-images.githubusercontent.com/3391958/164790410-eb2ccfad-5a2c-4061-8868-c104f67f8859.png)

**Comment by d1nuc0m** [comment]
> Hint customizations:
I'd say it works :)
