### ISSUE TITLE
Nav Options not developing anchor tags

### ISSUE THREAD

**Issue by bab014** [thegeeklab/hugo-geekdoc#382]
Not sure if it's me doing something wrong, but my nav file tree are not producing <a> tags within the <span> for the labels
```html
<li>
            <input type="checkbox" class="hidden"/>
            <label>
                <span class="flex">Pulling Quotes</span>  
            </label>
</li>
```
`Pulling Quotes` is a subsection in the content folder. I've used an `index.md` and `pulling-quotes.md`.

**Comment by xoxys** [comment]
I'm not sure what you mean. Could you please create a minimal example repo and describe the current and the expected behavior a bit more?

**Comment by bab014** [comment]
This was user error. 
I didn't realize there needed to be actual content in the page. 
My fault. Can be closed
