### ISSUE TITLE
Multilingual support broken if there is non-translated content

### ISSUE THREAD

**Issue by d1nuc0m** [thegeeklab/hugo-geekdoc#385]
As per title, the multilingual support works fine only as long as every content has its own translation.

Minimal reproducible example: [everythingTranslated.zip](https://github.com/thegeeklab/hugo-geekdoc/files/8542738/everythingTranslated.zip)
 
As per documentation "_Pages without a translation will be displayed in the selection list as well but are marked with an asterisk and link to the start page of the respective language._", but if there is a content that is not translated (aka the file only exists in a folder), the build will fail.

Minimal reproducible example: [somethingNotTranslated.zip](https://github.com/thegeeklab/hugo-geekdoc/files/8542753/somethingNotTranslated.zip)

Build error:
```bash
$ hugo server --verbose
INFO {DATE/TIME} Translation func for language it not found, use default.
Start building sites … 
hugo v0.96.0+extended linux/amd64 BuildDate=unknown
INFO {DATE/TIME} syncing static files to /
INFO {DATE/TIME} Rendering englishOnlyPage.adoc  using asciidoctor args [--no-header-footer -] ...
INFO {DATE/TIME} Rendering Page.adoc  using asciidoctor args [--no-header-footer -] ...
INFO {DATE/TIME} Rendering _index.adoc  using asciidoctor args [--no-header-footer -] ...
INFO {DATE/TIME} Rendering Page.adoc  using asciidoctor args [--no-header-footer -] ...
ERROR {DATE/TIME} [it] REF_NOT_FOUND: Ref "/englishOnlyPage" from page "_index.adoc": page not found
INFO {DATE/TIME} Rendering _index.adoc  using asciidoctor args [--no-header-footer -] ...
ERROR {DATE/TIME} [it] REF_NOT_FOUND: Ref "/englishOnlyPage" from page "Page.adoc": page not found
ERROR {DATE/TIME} [it] REF_NOT_FOUND: Ref "/englishOnlyPage" from page "tags": page not found
Error: Error building site: logged 3 error(s)
```

**Comment by xoxys** [comment]
Yes, that's "normal" as you hard-link the page to your navigation file `ref: "/englishOnlyPage"` and this file can't be found in one of the content dirs and I don't see a way how to fix this in the theme.

**Comment by d1nuc0m** [comment]
Ok, so actually is there a way to compile a site when some translation are missing? Disabling bundle menu?

**Comment by xoxys** [comment]
Yes, the only way right now is to disable bundle menu or symlink/copy the missing file to the `it` content folder.

**Comment by xoxys** [comment]
There might be a way to improve/fix this issue using `{{ relref . (dict "path" "about.md" "lang" "fr") }}` as described in https://gohugo.io/functions/relref/. I'll take a closer look after the admonition PR.

**Comment by d1nuc0m** [comment]
> Yes, the only way right now is to disable bundle menu or symlink/copy the missing file to the `it` content folder.

A simlink is an acceptable solution when working locally, but probably it would break when multiple contributor work on the same site through Git.

**Comment by d1nuc0m** [comment]
> There might be a way to improve/fix this issue using `{{ relref . (dict "path" "about.md" "lang" "fr") }}` as described in https://gohugo.io/functions/relref/. I'll take a closer look after the admonition PR.

Thank you
