### ISSUE TITLE
Hint icons break inside expand shortcode

### ISSUE THREAD

**Issue by demaerl** [thegeeklab/hugo-geekdoc#390]
After adding icons to [hint](https://geekdocs.de/shortcodes/hints/) titles in Geekdoc v.0.29.0, having a hint shortcode inside an [expand](https://geekdocs.de/shortcodes/expand/) shortcode is broken. The icon is not displayed correctly.

```
{{< expand "Optional settings">}}

{{< hint type=caution >}}
Dolor sit, sumo unique argument um no. Gracie nominal id xiv. Romanesque acclimates investiture. Ornateness bland it ex enc, est yeti am bongo detract re.
{{< /hint>}}

{{< /expand>}}
```
results in:

<img width="1112" alt="hint-inside-expand" src="https://user-images.githubusercontent.com/45464311/165694614-994f56bb-8531-40fa-98f9-0db3b92df4ae.png">

Is there a way to fix this or at least omit the icon?

Info:
Geekdoc v0.29.0
Hugo v0.97.3+extended

**Comment by xoxys** [comment]
Thanks for your report! I've created a PR already. Ill tag a bug fix release after the PR was merged.
