### ISSUE TITLE
mermaid shortcode doesn't render the nested box for a subgraph.

### ISSUE THREAD

**Issue by dkebler** [thegeeklab/hugo-geekdoc#424]
shortcode doesn't render the nested box for a subgraph.

works fine here
https://tinyurl.com/y4ge79rh

![image](https://user-images.githubusercontent.com/1316185/168885390-0f63eb64-87a7-498c-9c30-3ebb24677e9c.png)

but not within hugo shortcode.
```
{{< mermaid class="text-center">}}
flowchart TB
    c1-->a2
    subgraph one
    a1-->a2
    end
    subgraph two
    b1-->b2
    end
    subgraph three
    c1-->c2
    end
{{< /mermaid >}}
```

![image](https://user-images.githubusercontent.com/1316185/168885232-c07cf9b7-748e-48b4-b73d-bc24f3047420.png)

**Comment by xoxys** [comment]
Do you mean the yellow background? That might be related to the mermaid theme we use.

**Comment by xoxys** [comment]
Fixed. If that's not what you requested, please let me know.

**Comment by dkebler** [comment]
Finally got around to looking at your fix.  Yes it's good.  now subgraph boxes are "visible".  Thx.

![image](https://user-images.githubusercontent.com/1316185/173198536-39be9868-95e8-45fc-8376-05ead3b4af7f.png)
