### ISSUE TITLE
Footnotes inside hint shortcode cannot be placed in page footer

### ISSUE THREAD

**Issue by jnehlmeier** [thegeeklab/hugo-geekdoc#436]
Consider the following:

```markdown
{{<hint type=info title=Notice >}}
Some text with a footnote reference [^1]
{{< /hint >}}

[^1]: Footnote details on page footer
```

The above does not make an error and does not render the footnote at all. Instead the `[^1]` inside the hint block is rendered as text. I am not sure if that is an issue with this theme or a limitation in Hugo itself.

Workaround:
```markdown
{{<hint type=info title=Notice >}}
Some text with a footnote reference [^1]

[^1]: Footnote details on page footer
{{< /hint >}}
```

Now the footnote is rendered but it is rendered within the hint box which looks a bit weird.

**Comment by xoxys** [comment]
Thanks for the report. Even if I understand the issue, unfortunately I don't see a good way to handle it properly. This blog post is explaining the issue quite well, https://oostens.me/posts/hugo-shortcodes-with-markdown-gotchas/.

The post also mentions a solution but to be honest wrapping HTML constructs (and that's the main use case for shortcodes) into format strings is more a hack than a solution as it makes the maintenance and readability of shortcodes hard. Therefor, I'm going to mark this issue as `wont-fix` and would consider this as an upstream issue related to https://github.com/gohugoio/hugo/issues/5975

To still give you a way to fix the problem, you could just copy the shortcode from the theme to your site directory and override it with the mentioned workaround.

**Comment by jnehlmeier** [comment]
Thanks for the feedback and linked blog post. I can see why you won't fix it because the printf workaround really looks bad. I will think about either applying the workaround of changing the markdown structure a bit. I only have a few cases with footnotes within hints.
