### ISSUE TITLE
Supported Hugo version(s)?

### ISSUE THREAD

**Issue by Allaman** [thegeeklab/hugo-geekdoc#452]
Hello, recently I updated Hugo to v0.101 via brew and my page cannot be build anymore 
```
❯ hugo server --bind=0.0.0.0 --disableFastRender --log --verbose --buildDrafts
Start building sites …
hugo v0.101.0+extended darwin/arm64 BuildDate=unknown
Error: Error building site: "/Users/michael/workspace/github.com/allaman/rootknecht.net/content/knowledge/applications/gitlab/_index.md:1:1": timed out initializing value. You may have a circular loop in a shortcode, or your site may have resources that take longer to build than the `timeout` limit in your Hugo config file.
Built in 30345 ms
```
When I manually install my old v0.88 version the page is built fine 

```
❯ hugo server --bind=0.0.0.0 --disableFastRender --log --verbose --buildDrafts
Start building sites …
hugo v0.88.1-5BC54738 darwin/arm64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio

                   | EN
-------------------+------
  Pages            | 159
  Paginator pages  |   3
  Non-page files   |  84
  Static files     | 132
  Processed images | 316
  Aliases          |  23
  Sitemaps         |   1
  Cleaned          |   0

Built in 524 ms
```

I tried the latest release 0.32.4 geekdoc release as well as I am still on 0.18.3 without success.

Any hints are much appreciated

**Comment by xoxys** [comment]
Please see, https://github.com/thegeeklab/hugo-geekdoc/discussions/449 Right now I'm only aware of an issue related to the RenderString function used by some themes shortcodes. In your particular case I would need to debug a bit more what's happening as the errors is quiet "generic".

**Comment by xoxys** [comment]
You have a syntax issue:

```
diff --git a/content/knowledge/applications/gitlab/_index.md b/content/knowledge/applications/gitlab/_index.md
index f141b0e..7d41bfd 100644
--- a/content/knowledge/applications/gitlab/_index.md
+++ b/content/knowledge/applications/gitlab/_index.md
@@ -297,7 +297,7 @@ Add `openssl` to `environment.systemPackages`
 
 {{< hint info >}}
 Alternative: Use lets encrypt
-{{ /hint >}}
+{{< /hint >}}
 
 ### Gitlab configuration
```

It seems this is causing some kind of loop in Hugo v100+ and results in the observed timeout. As there is no way to fix this on the theme itself, I'm going to close this issue. You might want to consider to report/discuss this issue at https://discourse.gohugo.io/

**Comment by Allaman** [comment]
Thanks for your answer - just stumbled over it as well... 
- [update to v0.101.0](https://github.com/Allaman/rootknecht.net/commit/3c4220306c5596ac87bc72f816521f8e1187f8e7) is working
- [fix](https://github.com/Allaman/rootknecht.net/commit/dad9663942a8e2586390030f2c9ea27c6248febb
