### ISSUE TITLE
wrong links

### ISSUE THREAD

**Issue by MarcinKlejna** [thegeeklab/hugo-geekdoc#47]
no links are generated in the hint environment

https://ibb.co/9vCGpny
the same link displays correctly outside of the hint environment

**Comment by xoxys** [comment]
That looks like an upstream issue. Needs clarification.

**Comment by xoxys** [comment]
Hmm, I'm not really able to reproduce it:

```
{{< hint info >}}
**Markdown content**\
Dolor sit, sumo unique argument um no. Gracie nominal id xiv. Romanesque acclimates investiture.
Ornateness bland it ex enc, est yeti am bongo detract re. [test]({{< ref "toc.md#level-22" >}})
{{< /hint >}}
```

![grafik](https://user-images.githubusercontent.com/3391958/104245356-656c6f00-5464-11eb-823a-de7a6f875602.png)

Does other markdown work inside the shortcode? E.g.

```
{{< hint info >}}
**Bold** or [other link](google.de)
{{< /hint >}}
```

**Comment by MarcinKlejna** [comment]
Thank you for your answer and interest in the topic.

The problem was the spaces in the links.
Another error I noticed, the link `[7.4 Emergency files] ({{<ref "usr_07#7.4-Emergency-files">}})` does not take you to 7.4 header but displays the top of the page.

It's probably not a mistake, but I am doing something wrong

**Comment by xoxys** [comment]
In this case your anchor seems to be wrong (#7.4-Emergency-files). You can always find the right anchor generated by hugo if you inspect the headline:

![grafik](https://user-images.githubusercontent.com/3391958/104286484-65488f80-54b5-11eb-9814-b33a37cc8423.png)

Take a look on the right side, the `id` of the headline tag is the anchor. In this case it's `#level-1`.

**Comment by MarcinKlejna** [comment]
Yes, I was doing it wrong. Thank you for your help
