### ISSUE TITLE
Add size="original" to the img shortcode

### ISSUE THREAD

**Issue by dcermak** [thegeeklab/hugo-geekdoc#489]
First, thanks for this awesome theme!

I wanted to inquire whether it would be possible to add something like `size="original"` to the `img` shortcode, which would **not** resize the image at all? I find the current `img` shortcode very convenient, but the forced resizing of images makes images (especially small screenshots) look a bit odd.

**Comment by xoxys** [comment]
Thanks for your kind words. Sure, fine for me to add an `original` size :+1:

**Comment by dcermak** [comment]
Thanks a lot!
