### ISSUE TITLE
Why do posts end up on the news page?

### ISSUE THREAD

**Issue by fcooper8472** [thegeeklab/hugo-geekdoc#50]
This is probably a basic question... but why do the posts end up on the news page (rather than any other page)?

There does not appear to be anything in the `pages/_index.md` that would signify for the posts to be summarised on that page over any other.

Is it possible to move the news items to be summarised, say, after everything else on the homepage?

**Comment by xoxys** [comment]
Thanks for your report. What you try to achieve is not supported by this theme, sorry. Every subfolder of  the `content` folder is automatically resolved as a Hugo [content type](https://gohugo.io/content-management/types/). The rendered output of such content type is controlled by a layout, for  `posts` see [layouts/posts](https://github.com/thegeeklab/hugo-geekdoc/tree/master/layouts/posts). 

Hugo renders this content to `/posts` and you have to link this url somewhere. For the `exampleSite` this is done within the `more` menu, see https://github.com/thegeeklab/hugo-geekdoc/blob/master/exampleSite/data/menu/more.yaml#L4

**Comment by fcooper8472** [comment]
Got it, thanks for the quick reply. This answers my question, so I'll close the issue.
