### ISSUE TITLE
wrong class in "i18n/ja.yaml"

### ISSUE THREAD

**Issue by n-arakawa** [thegeeklab/hugo-geekdoc#502]
Class string for gdoc_heart in footer_build_with  may be wrong.
Compare with one in "en.yaml",  `class="icon gdoc_heart"` should reed `class="gdoc-icon gdoc_heart"`.
```
footer_build_with: >
  <a href="https://gohugo.io/" class="gdoc-footer__link">Hugo</a> でビルドしています。
  <svg class="icon gdoc_heart"><use xlink:href="#gdoc_heart"></use></svg>
```

**Comment by xoxys** [comment]
Thanks for your report!
