### ISSUE TITLE
feature request: add css-class for draft/expired/future documents.

### ISSUE THREAD

**Issue by n-arakawa** [thegeeklab/hugo-geekdoc#509]
Add some css-class to each of draft, expired and future documents so as to add decoration according to article status.

For example, add  "gdoc-status-draft" for draft document.

single
```
  <article
    class="gdoc-markdown gdoc-markdown__align--left gdoc-status-draft"
  >
```

list
```
<div class="gdoc-page">
  <article class="gdoc-post gdoc-status-draft">

```

and may be more.

**Comment by xoxys** [comment]
That's not possible, Hugo provides only a [page variable](https://gohugo.io/variables/page/) for `draft`, for future, expired and others we would need to implement a date comparison login on our own and that's something I don't want to maintain, sorry.

If you still want this feature, you can [override](https://gohugo.io/templates/lookup-order/#hugo-layouts-lookup-rules-with-theme) the template in your projects' layout folder.
