### ISSUE TITLE
Collapsing menus don't seem to work with bundle menu

### ISSUE THREAD

**Issue by fcooper8472** [thegeeklab/hugo-geekdoc#51]
I have set `geekdocMenuBundle` to `true` in my site configuration, and added

```
geekdocCollapseSection = true
```
to the topmatter of one of my `_index.md` files.

The menu is not collapsible, but when I go back to a file-tree menu it is.  Any ideas?

**Comment by xoxys** [comment]
Correct, collapsing is only supported for the file-tee menu as documented in https://geekdocs.de/usage/configuration/

**Comment by fcooper8472** [comment]
Thanks, missed that line in the documentation.

Do you think it would be fairly straightforward to edit the `menu-bundle` partial to include that functionality?  Perhaps with a parameter in the menu's yaml file? Or would it take a lot of re-working to do that?

**Comment by xoxys** [comment]
As the menu bundle works completely different I have not found a way to implememt it in a sufficient way. If someone would like to work on it I would be happy to review it.

**Comment by fcooper8472** [comment]
That patch seems to give me all the functionality I'm looking for - but I don't completely understand what it's doing, so it might well not be a general solution.

**Comment by fcooper8472** [comment]
Thanks for looking into this.

Your patch in #53 doesn't work for me: specifically, `$isParent` always returns `false` for every page other than the homepage. This is because `$numberOfPages` is zero for every page other than the homepage.

I'm not understanding all of the details: I don't understand why the `$isParent` is needed. Removing that check, and instead having

```
{{ $hasCollapse := and $this.Params.GeekdocCollapseSection (isset . "sub") }}
```

seems to result in the desired behaviour.

**Comment by xoxys** [comment]
Can you show me your ` data/menu.yaml` please?

**Comment by xoxys** [comment]
For me `$numberOfPages` looks like this (and that's what I would expect):

![grafik](https://user-images.githubusercontent.com/3391958/105616885-39dd7300-5dda-11eb-9465-da2754e563ac.png)

**Comment by xoxys** [comment]
But you are right, the `isParent/numberOfPages` check doesn't make sense for the menu bundle. In the file-tree menu we use it to verify that a hugo page object has existing child pages/sections what doesn't have to be the case for entries of the menu bundle. So, I removed it. Now it should work, but I would still be interested in an example data/menu.yaml file that you use :)

**Comment by fcooper8472** [comment]
Ok, thanks!

My yaml contains:
```
main:
  - name: Home
    ref: "/"
  - name: Page 1
    ref: "/page1"
    sub:
      - name: Page 1.1
        ref: "https://someSite"
        external: true
      - name: Page 1.2
        ref: "https://someOtherSite"
        external: true
```

which results in the following:
![nav](https://user-images.githubusercontent.com/3770306/105617146-16fc9000-5dd5-11eb-8e9a-3c1558fd8b3a.png)

**Comment by xoxys** [comment]
Yeah got it. Thats why checking the hugo page object doesnt make sense as external links refs can be used has nested elements 👍 thanks for sharing. I'll prepare a release tomorrow.

**Comment by fcooper8472** [comment]
Ah, awesome. Thanks so much for your help with this!

**Comment by xoxys** [comment]
Thank you too, glad to help.
