### ISSUE TITLE
render-codeblock-mermaid doesn't work

### ISSUE THREAD

**Issue by n-arakawa** [thegeeklab/hugo-geekdoc#538]
This bug is hidden when short code version of mermaid is used in the same page.
This is probably because these two share the same flag (`.Page.Scratch.mermaid`) and short code is evaluated before code blocks.

# error message 

```
Error: Error building site: "/tmp/demosite/content/test/test.md:5:1": "/tmp/demosite/layouts/_default/_markup/render-codeblock-mermaid.html:1:30": execute of template failed: template: _default/_markup/render-codeblock-mermaid.html:1:30: executing "_default/_markup/render-codeblock-mermaid.html" at <.Site>: can't evaluate field Site in type *codeblocks.codeBlockContext`
```

# work around

Add '.Page'  before '.Site' in layouts/_default/_markup/render-codeblock-mermaid.html

`<script defer src="{{ index (index .Site.Data.assets "mermaid.js") "src" | relURL }}"></script>`

=>

`<script defer src="{{ index (index .Page.Site.Data.assets "mermaid.js") "src" | relURL }}"></script>`

**Comment by xoxys** [comment]
Thanks for reporting!

Refs:
 - https://github.com/gohugoio/hugo/issues/6668
 - https://gohugo.io/variables/site/#get-the-site-object-from-a-partial

**Comment by n-arakawa** [comment]
F.Y.I 
hugo-geekdoc/layouts/_default/_markup/render-heading.html uses  '.Page.Site'

`{{- $showAnchor := (and (default true .Page.Params.GeekdocAnchor) (default true .Page.Site.Params.GeekdocAnchor)) -}}`

I'm not sure the difference between `site.XXX` and` .Page.Site.XXX`.

**Comment by xoxys** [comment]
https://github.com/thegeeklab/hugo-geekdoc/pull/541
