### ISSUE TITLE
Search field does not work

### ISSUE THREAD

**Issue by pshurgal** [thegeeklab/hugo-geekdoc#54]
Hello,

I am using hugo service with this theme with base url containing slashes like `www.domain.com/base`. And now I see an error in the developer console:
```
[HTTP/1.1 404 Not Found 93ms] GET https://domain.com/js/flexsearch-ad47a5e1ee.min.js
[HTTP/1.1 404 Not Found 49ms] GET https://domain.com/js/en.search-data.min.3f6252c4c9a592e70d3e2505bff277a3937d744ae3d90318ef06794865625de7.js
[HTTP/1.1 404 Not Found 55ms] GET https://domain.com/js/groupBy-62b30ac391.min.js
```
As you can see there is no `/base` inside URLs listed above. I have set some config variables for hugo to make all links absolute and everything works fine except search:
```
relativeURLs: false
canonifyURLs: true
```

**Comment by xoxys** [comment]
Thanks for your report. IMO this is a bug in Hugos handling if `canonifyURLs=true`. We load these scripts dynamically from another JS file that is processed as Hugo template, see https://github.com/thegeeklab/hugo-geekdoc/blob/master/assets/js/search.js#L17-L18. For whatever reason Hugo does not canonify these URLs... 

Maybe absURL would be a workaround, but I would like to check this behavior first. I'll open a post in the Hugo forum and try to clarify this.

**Comment by xoxys** [comment]
https://discourse.gohugo.io/t/canonifyurls-does-not-work-with-executeastemplate/30852

**Comment by xoxys** [comment]
Looks like that's not that simple to implement... @pshurgal Is absolute URLs a hard requirement for you? What's the background?

**Comment by pshurgal** [comment]
Hello, absolute path is not required actually, but I need that the script has path `/base/js/flexsearch-ad47a5e1ee.min.js` but not `/js/flexsearch-ad47a5e1ee.min.js` as I my service has base url `www.domain.com/base` but not `www.domain.com`.

**Comment by xoxys** [comment]
Have you just tried `baseURL: https://example.com/test` without relativeURLs or canonifyURLs? That works for me with latest Hugo v0.80:

```
<script defer src="/test/js/en.search.min.c664797beec65c51f49930100e4be2abb1a2072dba2787e4c782ce94ca83df7c.js"></script>

...

loadScript('/test/js/flexsearch-ad47a5e1ee.min.js',func
```

**Comment by pshurgal** [comment]
Yes, I have tried it but images are not displayed in this case because they have incorrect relative urls without `/base`

**Comment by xoxys** [comment]
How do you embed images? The default hugo `figure` shortcode?

**Comment by pshurgal** [comment]
`![](image/url.jpeg)`

**Comment by xoxys** [comment]
Ok markdown. There is an official shortcode for pages https://gohugo.io/content-management/shortcodes/#example-ref-and-relref-input but that will not work for resources like images. What we could do is adding a custom shortcode to the theme that will work like this:

```
[![Example file-tree menu]({{< resource "media/file-tree.png" >}})]({{< resource "media/file-tree.png" >}})
```

Result:

```
<p>
    <a href="/base/media/file-tree.png">
        <img src="/base/media/file-tree.png" alt="Example file-tree menu">
    </a>
</p>
```

Could this work for you?

**Comment by pshurgal** [comment]
ofc not, this is not solution of the problem and looks rly ugly

**Comment by xoxys** [comment]
Well then I don't see a good way to fix this in the theme right now, sorry.

**Comment by xoxys** [comment]
https://github.com/gohugoio/hugo/issues/8078

**Comment by xoxys** [comment]
@pshurgal I've applied a fix to the `render-templates` branch. Could you build and test the theme from this branch? It should work now out of the box without `relativeURLs` and `canonifyURLs`.
