### ISSUE TITLE
shortcode img can't handle SVG

### ISSUE THREAD

**Issue by n-arakawa** [thegeeklab/hugo-geekdoc#547]
This is just a edge case.

`{{<img name="sample.svg">}}`

=>

`failed to render shortcode "img": failed to process shortcode: "/tmp/site/themes/hugo-geekdoc/layouts/shortcodes/img.html:10:19": execute of template failed at <.Fill>: error calling Fill: this method is only available for raster images. To determine if an image is SVG, you can do {{ if eq .MediaType.SubType "svg" }}{{ end }} `

**Comment by xoxys** [comment]
Basic support to render SVG via the `img` shortcode added with the linked PR. As handling the size of SVG images dynamically is quite difficult, the support is limited.
