### ISSUE TITLE
template: partials/title.html:11: function "return" not defined

### ISSUE THREAD

**Issue by p-mathis** [thegeeklab/hugo-geekdoc#55]
Hello,

Deploying my site on Netlify raises the error :  

`Error: "/opt/build/repo/themes/hugo-geekdoc/layouts/partials/title.html:11:1": parse failed: template: partials/title.html:11: function "return" not defined`  

I am using `hugo v0.72.0` and `hugo-geekdoc : v0.8.3`

Have you any idea of what happens and how to fix the problem ?  
Thanks for your help.

**Comment by xoxys** [comment]
Hello, please take a look on an older issue https://github.com/thegeeklab/hugo-geekdoc/issues/46

You can not use this theme from a branch directly as described in the docs and the readme.

**Comment by p-mathis** [comment]
Hello,
Your answer helped me. Even if it was a bit difficult for me to understand, my computer level being low. Everything works. Thank you.
