### ISSUE TITLE
.geekdoc-markdown h1 elements has larger font than line-height

### ISSUE THREAD

**Issue by edruid** [thegeeklab/hugo-geekdoc#57]
Any `h1` elements within the `article.gdoc-markdown` elements gets `font-size: 2em` from `h1` and `line-height: 1.6em` from `.gdoc-markdown` (both in main.css). If the title is long enough (and/or screen is small enough) to wrap around this makes the text render on top of itself.

Suggestion: add to main.css
```
.gdoc-markdown h1 {
    line-height: 2rem
}
```

**Comment by xoxys** [comment]
Thanks for your report. Right now, I'm not able to reproduce it, no overlay so far.

![grafik](https://user-images.githubusercontent.com/3391958/107145435-b37c7180-6941-11eb-9a63-baeafc41f9ff.png)

**Comment by edruid** [comment]
Use qpgj as well, it's the tails overlapping dots (like in ijåäö) that are most hard to read (at least if your language has both with and without dots)

**Comment by xoxys** [comment]
Should be fixed now. Let me know if there are still problems.
