### ISSUE TITLE
400 Bad Request in response to https://geekdocs.de/usage/getting-started/img/geekdoc-stack.svg

### ISSUE THREAD

**Issue by inputvalidation** [thegeeklab/hugo-geekdoc#590]
We were investigating 404 response in our own Geekdoc based Hugo site. It appears as if the Geekdoc CSS is attempting to load img/geekdoc-stack.svg from a relative path (somewhere) and not the absolute one. We found out this is also happening on Geekdoc's own Getting Started page (although there it becomes a 400), so that might make it easier to identify.

<img width="1148" alt="Screenshot 2023-02-22 at 20 59 41" src="https://user-images.githubusercontent.com/26655367/220746618-4277cd7e-8cf7-41cc-b98e-43ae888d71d7.png">

**Comment by xoxys** [comment]
I'm not able to reproduce it. At least in Chrome and FF tit works for me.

![image](https://user-images.githubusercontent.com/3391958/220747974-0a680287-4aec-403b-a3ca-5179cec94b74.png)

**Comment by inputvalidation** [comment]
Hi @xoxys, thanks for the fast reply! Turns out this appears to be caused by the Dark Reader extension in Chrome, I'll report it to their Github project.
