### ISSUE TITLE
Clarification on file tree menus

### ISSUE THREAD

**Issue by rgov** [thegeeklab/hugo-geekdoc#60]
https://geekdocs.de/usage/menus/#file-tree-menu

This says that single files are not supported, yet the example file tree shows two single files, `level-2-1.md` and `level-2-2.md` which **do** show up in the menu.

Is this a mistake?

**Comment by rgov** [comment]
In my experiment, single files that are inside a directory with an `_index.md` file *do* show up in the ToC, but ones that are at the top level do not.

**Comment by xoxys** [comment]
Have you read the linked hugo documentation about page bundles? Thats the only supported content structure. As level-2-* files are part of a page bundle they will show up. Files outside of a page bundle will not.

Open for suggestion to make it more clear in the docs.

**Comment by xoxys** [comment]
Please open a new issue if you have further questions.
