### ISSUE TITLE
Print version truncated in firefox

### ISSUE THREAD

**Issue by edruid** [thegeeklab/hugo-geekdoc#61]
In firefox (85.0.1 (64-bit) for Ubuntu) pages with images gets truncated.

Steps to reproduce:
1. In firefox go to https://geekdocs.de/usage/menus/
2. Open print preview dialog (Ctrl+p (or command+p?))
3. At the bottom, notice that the final image is truncated and the footer is hidden behind the image only showing part of the leading B.

I'm not sure what causes this. Rendering the print version directly in firefox works fine, it is only the print that doesn't work. I "solved" this on my site by hiding the footer and adding `body{overflow-x: visible}` in the print css.

This may very well be a firefox bug rather than a geekdoc one.

**Comment by xoxys** [comment]
Yeah, printing websites is still crap :smile: I had a really hard time to get a more or less working print.css... I'll take a closer look but not sure if I want to put more effort into it right now.

**Comment by i7d3v3l0p3r** [comment]
@edruid Should be fixed by #72

**Comment by edruid** [comment]
@i7d3v3l0p3r  Nice! Thanks!
