### ISSUE TITLE
Title splite based on capitla letters is broken

### ISSUE THREAD

**Issue by leahoswald** [thegeeklab/hugo-geekdoc#62]
We have some documentation sites that have parts in capital letters in their title. For example the shortcut OSPF or BGP. It looks like there is an automation that adds a whitespace after every capital letter and this breaks these titles. I would suggest to limit this behavior to some delimiters like - and _ or make it configurable.

![Screenshot2021-02-12_23-17-36](https://user-images.githubusercontent.com/1292551/107828533-53def580-6d89-11eb-8de8-7e5d10c48aba.png)

**Comment by xoxys** [comment]
Thanks for your report. I was able to reproduce it and try to look into it during the next days. In the meantime you could work around it by overwriting the title in the front matter of the file e.g. 

```Markdown
---
title: Test OSPF
---

Dummy content...
```

**Comment by leahoswald** [comment]
Thank you. And sorry, forgot to mention that it only happens if the title was derived from the filename.

**Comment by xoxys** [comment]
No worries. Sadly I don't see a way to fix this easily as this might be related to https://github.com/gohugoio/hugo/issues/7912. Right now, we use a Hugo partial to generate the title of a page based on the information we get, see https://github.com/thegeeklab/hugo-geekdoc/blob/master/layouts/partials/title.html

If no title parameter is set (e.g. within the front matter) we try to use the file/directory name and the `humanize` + `title` filter to auto-convert the filename into a proper headline.

I've prepared a PR adding a parameter `geekdocRawTitle: false`. If this option is set to `true` the raw file/directory name will be used as title without further formatting, but this requires to use clear filenames all over the place e.g. `Router OSPFv3 Ex Start Fix.md` with correct capitalizing, spacing and so on.

Let me know if this will work for you.

**Comment by leahoswald** [comment]
Thanks for the feedback! In this case I don't think the config option is a good solution for us and most other people. I think we will go with the title in the front matter. This is also much easier to put into a template for new sites than to explain everyone how the filename is properly formatted. Thanks for your help anyway. From my side the issue could be close.
