### ISSUE TITLE
Static files not working

### ISSUE THREAD

**Issue by i7d3v3l0p3r** [thegeeklab/hugo-geekdoc#64]
When use static files (images) inside Expand shortcode, complete path is to this file is incorrect

```md
{{< expand "Spoiler" >}}
![1](dirInStatic/1.jpg) <-- not working
{{< /expand >}}

![1](dirInStatic/1.jpg) <-- working
```

**Comment by i7d3v3l0p3r** [comment]
After change `{{ .Inner | markdownify }}` to `{{ with .Inner }} {{ $.Page.RenderString . }} {{ end }}` in file `themes\hugo-geekdoc\layouts\shortcodes\expand.html` image displayed correctly

**Comment by xoxys** [comment]
Thanks for your report. Good catch! As we already have custom render hooks in place I've replaced all `markdownify` so that the render hooks get always used.

**Comment by xoxys** [comment]
I have tagged a new version. Please let me know if you still have problems.
