### ISSUE TITLE
Support for NodeJS 20

### ISSUE THREAD

**Issue by JokaJukka** [thegeeklab/hugo-geekdoc#641]
Hey there!
As NodeJS 20 was released ~2 months ago, how is the geekdoc support for this version looking?

**Comment by xoxys** [comment]
Hi, we only support the current LTS release of node, sorry. You can replace the `.npmrc` of this repo to disable the strict version check for node, but in this case, we can't accept issues related to an unsupported node version.

**Comment by JokaJukka** [comment]
Hey there!
To my knowledge, current LTS is Node 20. Do you plan to support it?
Perhaps this should be re-opened.

**Comment by xoxys** [comment]
> To my knowledge, current LTS is Node 20. Do you plan to support it?

It is supported already https://github.com/thegeeklab/hugo-geekdoc/blob/main/package.json#L34 and its also used for our release builds.
