### ISSUE TITLE
Spacing out `include` of `.md.part` from `youtube` if has only one line

### ISSUE THREAD

**Issue by jamesbraza** [thegeeklab/hugo-geekdoc#645]
Here is a `file.md.part`:

```md
Test
```

Here is a `file.md`:

```md
---
title: File
---

{{< include file="/file.md.part" >}}

{{< youtube -dJolYw8tnk >}}
```

It renders without any space below the text, and looks cramped:

![one line file rendering](https://github.com/thegeeklab/hugo-geekdoc/assets/8990777/f810c653-0f90-42d5-8bf5-601e608d29b9)

Next, if you make the `.md.part` have multiple lines, the rendering suddenly adds space below the `include`:

```md
Test

Test
```

![multiline file rendering](https://github.com/thegeeklab/hugo-geekdoc/assets/8990777/249d66e2-5301-4ca7-b1c0-667fbc0b7c56)

Unfortunately, use of `<br />` or `&nbsp;` adds too much vertical whitespace.

Can Geekdocs automatically add space below the single-line `include` of a `.md.part`?

Alternately, can Geekdocs have the ability to insert a small vertical space between two lines?

**Comment by jamesbraza** [comment]
Fwiw, this `<pre>` hack seems accomplishes the job:

```md
Text
&nbsp;<pre></pre>
```

**Comment by xoxys** [comment]
The behavior is not related to the theme and affects all short codes, not only the custom `include` shortcode. Adding two or more `youtube` shortcodes right after each other will also not render a spacing.

You might want to take a look at https://github.com/gohugoio/hugo/issues/1642 where also some workarounds are described. 

Why you don't want to use 

```
{{< youtube -dJolYw8tnk >}}
<br \>
{{< youtube -dJolYw8tnk >}}
```

or 

```
{{< youtube -dJolYw8tnk >}}
\
{{< youtube -dJolYw8tnk >}}
```

is a bit unclear to me because both variants are shorter and the spacing is smaller that what `&nbsp;<pre></pre>` creates, at least for me.

**Comment by jamesbraza** [comment]
Okay I follow.  For me in the `.md` content file:

| `\` | `<br />` | `<p></p>` |
|---|---|---|
| <img width="157" alt="Screen Shot 2023-06-22 at 12 33 35 AM" src="https://github.com/thegeeklab/hugo-geekdoc/assets/8990777/a5f340ae-2e65-4cd4-8ba5-6e504e0e7b22"> | <img width="157" alt="Screen Shot 2023-06-22 at 12 32 54 AM" src="https://github.com/thegeeklab/hugo-geekdoc/assets/8990777/c2f9153b-6382-4123-8765-96e76df16c58"> | <img width="157" alt="Screen Shot 2023-06-22 at 12 34 03 AM" src="https://github.com/thegeeklab/hugo-geekdoc/assets/8990777/b1f14ef0-da19-4796-b904-b457bdceecde"> |

We can see `<p></p>` has slightly less spacing.  It matches using `&nbsp;<pre></pre>` at the bottom of the `.md.part` file.

---

Thanks @xoxys for sharing a relevant link.  Since it seems the bug is outside of this theme, I will close this out!

Feel free to reopen or follow up! 👌
