### ISSUE TITLE
官网页面Edit按钮的超链接失效

### ISSUE THREAD

**Issue by y19941115mx** [thegeeklab/hugo-geekdoc#663]
![image](https://github.com/thegeeklab/hugo-geekdoc/assets/15321461/0c471309-da70-4bed-9145-0fab95f06b3c)
![image](https://github.com/thegeeklab/hugo-geekdoc/assets/15321461/9e954930-1f48-43a0-9d71-607dcf7f81be)
需要修改按钮的超链接地址

**Comment by xoxys** [comment]
Thanks. Please write issues in English. Hugo has changed its behavior, needs clarification: https://github.com/gohugoio/hugo/issues/11237
