### ISSUE TITLE
XML not highlighted in the expand shortcode.

### ISSUE THREAD

**Issue by vhorvat** [thegeeklab/hugo-geekdoc#666]
Hello!
While using Hugo powered page for my personal project I use expand shortcode in conjunction with code highlighting function and if the code in the expand block is XML it’s not highlighted as it should be but parsed instead.

I figured out that if I remove htmlUnescape function from the expand shortcode, everything works fine.
My question is whether is this by design or is this indeed a bug since I don't really know the background why htmlUnescape is used here. If I choose any other programming language to be used for the highlighting inside expand shortcode everything works as regular.

Is there a different proposed way to use expand + highlight function while working with XML?

Thank you!

With unEscape function enabled:
![Snimka zaslona 2023-07-11 130507](https://github.com/thegeeklab/hugo-geekdoc/assets/37957537/89d814e9-82c6-409b-b725-c0202da69f4f)

With unEscape function removed (and as it should be):
![252644846-8197ffaa-4d7e-49e1-944e-a0da8f4d645e](https://github.com/thegeeklab/hugo-geekdoc/assets/37957537/26e10afc-c3b4-4028-a30b-d7c8aa6bbe2b)

Sample code:
https://gist.github.com/vhorvat/f5071d6e4b191d1829641772d94d959b

I use v115.2 of Hugo and latest Geekdoc version.

**Comment by xoxys** [comment]
Hi, thanks for your report. This workaround was introduced in https://github.com/thegeeklab/hugo-geekdoc/pull/415, but I'm not able to reproduce the formatting issue anymore. I will remove `htmlUnescape` function from the short code for now.

**Comment by vhorvat** [comment]
Thank you for your fast reply!
