### ISSUE TITLE
post page need tag function

### ISSUE THREAD

**Issue by xied5531** [thegeeklab/hugo-geekdoc#68]

**Comment by xoxys** [comment]
@xied5531 Please add more information and describe your use case. The posts section is intended to be used for e.g. release information and not as a feature-complete blog.

**Comment by xied5531** [comment]
I use post as blog, so need tag page in order to read better, thank you

**Comment by heloise-lamaury** [comment]
Hello,
So tags are not supported by the theme, that's fine. For our own needs, we will implement tag support in Geekdoc.
@xoxors would you welcome a contribution for this? Are there any special things to know, to take care of?
Thanks!

**Comment by xoxys** [comment]
Hi, sure contributions are always welcome. The posts section in hugo-geekdoc is a subset implementation of [hugo-geekblog](https://github.com/thegeeklab/hugo-geekblog). Porting the tag handling from this theme would be sufficient, as I would like to keep the structure of both themes as close as possible. The only thing that need to be adapted for hugo-geekdoc is the integration in the side nav.

**Comment by xoxys** [comment]
@heloise-lamaury I've created a PR to implement tags for posts. Maybe you want to take a look?
