### ISSUE TITLE
FlexSearch does not work on Safari

### ISSUE THREAD

**Issue by KrisSimon** [thegeeklab/hugo-geekdoc#695]
On Safari (Version 16.6 (18615.3.12.11.2)) the search result panel pops up, but i can not click an item. The click-event  is lost somewhere. The page stays the same.

**Comment by KrisSimon** [comment]
Hi, yap it is reproducible on geekdocks. 
Here are two screenshots from my project showing the event.
<img width="1420" alt="Screenshot 2023-08-30 at 10 09 31" src="https://github.com/thegeeklab/hugo-geekdoc/assets/142403270/b25a9547-dd49-493c-a642-b35153a654de">
<img width="1420" alt="Screenshot 2023-08-30 at 10 10 57" src="https://github.com/thegeeklab/hugo-geekdoc/assets/142403270/f5f188c4-f387-4fc0-9c7c-860a93795326">

**Comment by KrisSimon** [comment]
I got it! 
It is a css issue, I fix it and do PR.

**Comment by KrisSimon** [comment]
https://github.com/thegeeklab/hugo-geekdoc/pull/696

**Comment by xoxys** [comment]
Closed by https://github.com/thegeeklab/hugo-geekdoc/pull/696
