### ISSUE TITLE
Provide a way to show "Next" and "Previous" links on a page

### ISSUE THREAD

**Issue by Miepee** [thegeeklab/hugo-geekdoc#720]
Something akin to this (very quickly hacked together)
![grafik](https://github.com/thegeeklab/hugo-geekdoc/assets/38186597/5930fe35-da87-4869-85a1-bf7d9468c6ae)

I.e. using the example page, what i'd like to see:
- Level 1
  - Level 1.1
  - Level 1.2
- Level 2
  - Level 2.1
  - Level 2.2
  
 If one is on `Level 2` then Previous would go to `Level 1.2`, while Next would go to `Level 2.1`. If one is on `Level 1.1`, then Previous goes to `Level 1` and Next goes to `Level 1.2`.
 What should happen on `Level 1`, I'm not quite sure. Maybe Previous shouldn't show up at all. Or maybe it should also just link to the root (in this case `Collapse`).

Would be neat to have it possible to dis/enable it on a global level, as well as per page.

Read the docs has a nicer implementation of it if anyone would like to have another reference (scroll down all the way to the bottom):
https://docs.readthedocs.io/en/stable/tutorial/index.html

**Comment by xoxys** [comment]
This works already using the bundle menu https://geekdocs.de/usage/menus/#bundle-menu.

You can see it in action in this example https://ansible-later.geekdocs.de/setup/pip/

**Comment by Miepee** [comment]
Hmm, would it be out of scope to also provide that for the file tree menus?
Not a blocker for me, just asking out of curiosity.

**Comment by xoxys** [comment]
> Hmm, would it be out of scope to also provide that for the file tree menus?

Need to check again, IIRC there was a reason why we have not added it to the file tree menu.

> Not sure right whether this feature doesn't exist, or whether it was forgotten to add there.

Just missing in the docs.

**Comment by xoxys** [comment]
Checked the docs, It's already there, see https://geekdocs.de/usage/configuration/#site-configuration

**Comment by xoxys** [comment]
@Miepee Would you be able to give it a try from the main branch of the repo?

**Comment by xoxys** [comment]
Would still be interested in your feedback, just add it to this issue.

**Comment by Miepee** [comment]
Sorry for answering that late.
Wanted to test it just now, but I seem to have problems packing the theme from source:

```
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: geekdoc@1.0.0
npm ERR! notsup Not compatible with your version of node/npm: geekdoc@1.0.0
npm ERR! notsup Required: {"node":">=16.15 <=18"}
npm ERR! notsup Actual:   {"npm":"10.2.0","node":"v20.8.0"}

```

I am on Arch Linux, and currently can't find a way to downgrade node.

**Comment by xoxys** [comment]
No worries, I can just tag a release later.

**Comment by Miepee** [comment]
Sorry for the late response, just saw the release. Seems to work as expected on file trees :)
