### ISSUE TITLE
Suggestion: add disable pluralizelisttitles by default

### ISSUE THREAD

**Issue by leahoswald** [thegeeklab/hugo-geekdoc#73]
Hugo does try to pluralize folder titles by default. For actual pages this is no problem with the title defined in the frontmatter but for folders it's rather annoying to get something like "Securities" or "Hardwares" instead of just "Security" or "Hardware". Therefore I would suggest to add `pluralizelisttitles = false` as a default for the recommended config in the docs.

**Comment by xoxys** [comment]
Thanks for your report. What's your current Hugo version? Do you have an example how to reproduce it? Even with this bundle structure (all files empty), titles are not pluralized by default:

```
content/
├── hardware
│   ├── hardware.md
│   └── _index.md
```

**Comment by leahoswald** [comment]
My hugo version is:  v0.80.0/extended (from arch linux repository)

I just tested it with this structure in a new projekt. All .md files empty. Latest version of geekdoc.
```
content/
├── hardware
│   └── switch.md
└── security
    └── firewall.md
```

Config:
```
baseURL = "http://localhost"
title = "Ops Docs"
theme = "hugo-geekdoc"

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

[params]
geekdocSearchShowParent = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9
```

The result:
![Screenshot2021-02-22_14-10-25](https://user-images.githubusercontent.com/1292551/108713231-3859b480-7518-11eb-863e-16234e724f3a.png)

**Comment by xoxys** [comment]
Thanks! That's somehow a bit inconsistent Hugo behavior as it is not affecting page bundles... Anyway, I'll add it to the docs to avoid confusion. Besides that I would recommend to always use page bundles to organize your content, see http://localhost:1313/usage/menus/#file-tree-menu.

**Comment by xoxys** [comment]
Fixed by https://github.com/thegeeklab/hugo-geekdoc/commit/dc8740d28c3ca50403ad098f1f3231bf75878052
