### ISSUE TITLE
Table of Contents shortcode needs better documentation on difference between html and raw

### ISSUE THREAD

**Issue by Miepee** [thegeeklab/hugo-geekdoc#731]
See title.
Repro case:
```md
{{<expand>}}
{{<toc>}}
{{</expand >}}

# foobar
```
![grafik](https://github.com/thegeeklab/hugo-geekdoc/assets/38186597/53803176-8824-4cb3-aee8-e0e5ccaa091f)

**Comment by xoxys** [comment]
Please use `format=raw` for more details see https://geekdocs.de/shortcodes/toc/

**Comment by Miepee** [comment]
Unfortunately, I don't really see any details on that page. From reading there, I can't seem to find any clue what the actual difference is between `html` and `raw` for `format`, only that I *can* change it :/

**Comment by xoxys** [comment]
Yes, html will always add a horizontal line. Agree needs docs improvement.

**Comment by Miepee** [comment]
Cool.
Also just found the source code for that here: https://github.com/thegeeklab/hugo-geekdoc/blob/76ef8f147cc98f0daae2e4e8aa0c3bb6b7ac2c93/layouts/shortcodes/toc.html#L8

I'll change the title to reflect this, thanks :)
