### ISSUE TITLE
Collapse Arrow-Down icon is hidden with Menu Bundle

### ISSUE THREAD

**Issue by Miepee** [thegeeklab/hugo-geekdoc#737]
With file-tree:
![grafik](https://github.com/thegeeklab/hugo-geekdoc/assets/38186597/844cb20b-c005-433a-bd7f-c1057d3ecbce)
![grafik](https://github.com/thegeeklab/hugo-geekdoc/assets/38186597/4109de1b-42d2-4da6-903a-b83bb62fc364)

With MenuBundle:
![grafik](https://github.com/thegeeklab/hugo-geekdoc/assets/38186597/fe9a20cb-a7e6-45d3-9ce5-069bf779df8c)
![grafik](https://github.com/thegeeklab/hugo-geekdoc/assets/38186597/ae01dd32-6705-4d70-87f5-118f3770c8d1)
For some reason it has a hidden class when opened in the menu bundle:
![grafik](https://github.com/thegeeklab/hugo-geekdoc/assets/38186597/e07f40d0-01d6-40fe-9d17-d4d13e39b694)

**Comment by xoxys** [comment]
Please provide a reproduction example.

**Comment by Miepee** [comment]
Ahh, sorry.
My menu/main.yaml looks like this:
```yaml
- name: Assets
  ref: "/assets"
  sub:
    - name: foo
      ref: "/assets/foo"
   - name: bar
     ref: "/assets/bar"
```
then `assets/_index.md` looks like this:
```md
---
title: Assets
geekdocCollapseSection: true
----
The asset page
```

with `assets/foo/_index.md` and `assets/bar/_index.md` looking like this:
```md
---
title: Foo
---
foo page
```
```md
---
title: Bar
---
bar page
```


I can then reproduce the bug if I have `geekdocMenuBundle` set to true in the `config.toml`. If it's set to false, the bug doesnt appear.
