### ISSUE TITLE
Incorrect rendering of code block in list item

### ISSUE THREAD

**Issue by jcrd** [thegeeklab/hugo-geekdoc#74]
Markdown with a code block indented under a list item is rendered incorrectly.

```
* test

  \```
  bad
  indent
  \```
```
The above (minus escaping) produces:
![image](https://user-images.githubusercontent.com/44040597/108795990-e9764400-7544-11eb-9b5f-a75c93b3489c.png)

**Comment by xoxys** [comment]
Thanks for your report! Should be fixed in the latest release v0.9.4

**Comment by jcrd** [comment]
Thanks for the quick fix!
