### ISSUE TITLE
Do not use`.Site.BaseURL`

### ISSUE THREAD

**Issue by flexxindicomplex** [thegeeklab/hugo-geekdoc#756]
It was never meant to be exposed to templates, and Hugo maintainers are also discouraging it. Use `absURL` or `absLangURL` instead (or `.Site.Home.Permalink`)

**Comment by xoxys** [comment]
Thanks for your issue.

> It was never meant to be exposed to templates, and Hugo maintainers are also discouraging it.

Do you have a ref for this? Even if it was not intended to be exposed it is for a long time now and its also documented in the official docs.

**Comment by flexxindicomplex** [comment]
> Do you have a ref for this?

https://discourse.gohugo.io/t/46692/4
