### ISSUE TITLE
FontAwesome & other Icons - Clarification Question

### ISSUE THREAD

**Issue by aNerdgirl** [thegeeklab/hugo-geekdoc#78]
First of all, thank you for the nice and clean theme.
I have a clarification question: In the more.yml file I can specify Icons for each list entry. However, how are the icons identified? Which keywords are available to use?

In general: Which Icons (also FontAwesome?) are available and how can I use them in the posts?

Sorry, I checked the documentation, but couldn't find it.

**Comment by xoxys** [comment]
Thanks for your report. You are right, the documentation is still lacking detail information about the icons. We'll try to address this during the next days. In the meantime you can take a look at https://github.com/thegeeklab/hugo-geekdoc/tree/master/src/icons This folder holds all icons that are available. You have to use the file name to reference the icon in the menu.

Some background:
Built-in icons coming from multiple sources. During the theme release build, the source SVG icons are converted into an SVG sprite and an iconfont. For the menu only icons from an embedded SVG sprite are supported, see https://github.com/thegeeklab/hugo-geekdoc/blob/master/layouts/partials/menu-bundle.html#L32.

If you want to extend the icons you can create your own SVG sprite e.g. with some cloud tools like https://svgsprit.es/ The resulting sprite need to be saved in an HTML file and must be included in https://github.com/thegeeklab/hugo-geekdoc/blob/e29fa7a32794a05acc3888dd2ceaa170a01c08af/layouts/_default/baseof.html#L9. The ugly part, this requires a deeper understanding of Hugos template lookup order and the ability to customize a Theme. As I'm aware that this process isn't straight forward nor documented and tested, it needs improvements as well.

**Comment by aNerdgirl** [comment]
Thank you very much for the detailed answer and quick reply.
Wouldn't the use of FontAwesome a easy solution for implementing a lot of icons, without the need of a deeper understanding ofd Hugos template lookup (at least for the user)?
Anyway, I don't have much knowledge on that topic, so I don't want to talk you into anything :D Thank you for all the work!

**Comment by xoxys** [comment]
The main idea was to keep the theme and its size as small as possible. But I still agree, the current situation isn't that simple for users. Need to think a bit more about it :)

**Comment by xoxys** [comment]
@aNerdgirl Using custom icon sets should be much easier now. Check out our latest release and the new autoload mechanism https://geekdocs.de/usage/icons/ Hope that works for you :)
