### ISSUE TITLE
Underline offset

### ISSUE THREAD

**Issue by i7d3v3l0p3r** [thegeeklab/hugo-geekdoc#80]
What about to add underline offset on active links? `text-underline-offset: 1px`

Before:
![image](https://user-images.githubusercontent.com/56602205/109431969-17aec480-7a1a-11eb-9d0b-3b71aa05e14f.png)

After:
![image](https://user-images.githubusercontent.com/56602205/109431991-25644a00-7a1a-11eb-9854-8d7e9c840469.png)

**Comment by xoxys** [comment]
What's your browser? Not sure about it as it looks pretty fine already for me in Chromium and Firefox.

![grafik](https://user-images.githubusercontent.com/3391958/109566082-a76c7580-7ae3-11eb-80bf-bd1cd5222ad3.png)

![grafik](https://user-images.githubusercontent.com/3391958/109566136-bbb07280-7ae3-11eb-8251-f57ce8d94054.png)

**Comment by i7d3v3l0p3r** [comment]
Sorry my mistake, after update to latest version it looks nice
