### ISSUE TITLE
Minified build removes space in site footer

### ISSUE THREAD

**Issue by jcrd** [thegeeklab/hugo-geekdoc#81]
Building with `hugo --minify` combines the lines in [this span element](https://github.com/thegeeklab/hugo-geekdoc/blob/master/layouts/partials/site-footer.html#L3) so there is no space between 'and' and the heart:

![image](https://user-images.githubusercontent.com/44040597/109732345-3e840c80-7b7a-11eb-9a5c-eb52097a10b7.png)

**Comment by xoxys** [comment]
Thanks for your report! We'll look into this.

**Comment by xoxys** [comment]
After some testing I have to say we will not spend effort on this. It's not just the heart but also some other places where spaces between HTML elements... Some of these issues are related to https://github.com/gohugoio/hugo/issues/6892. As the benefit is very low compared to the required afford, sorry. While recommendation like "don't depend on whitespace in your layout" sounds nice, it seems to be not that straight forward especially for something like embedded icons into the text flow.

The recommendation for this theme is to disable HTML in the minify options:

```
minify:
  disableHTML: true
```
