### ISSUE TITLE
Conflict between hint and code block

### ISSUE THREAD

**Issue by jcs090218** [thegeeklab/hugo-geekdoc#838]
The following

```md
{{< hint ok >}}
💡 Optionally, you can use `--show-hidden` to show all available commands and
options!
{{< /hint >}}
```

will render:
![2024-06-06 20 26 34](https://github.com/thegeeklab/hugo-geekdoc/assets/8685505/5c413ea1-8047-45b7-b46a-ec3c2a860022)

**Comment by xoxys** [comment]
Looks like the intended result. Can you describe the conflict more detailed?

**Comment by jcs090218** [comment]
The code block's background color in the tip block doesn't respect the tip's background color. 🤔

**Comment by xoxys** [comment]
Its still a code block and its intended highlight them. What would be your suggestion?

**Comment by xoxys** [comment]
What do you think?

![image](https://github.com/thegeeklab/hugo-geekdoc/assets/3391958/0897021e-28cd-4dcf-a765-32ae0ec9322a)
![image](https://github.com/thegeeklab/hugo-geekdoc/assets/3391958/d23c9820-2996-4828-8a5c-c5603f07884a)

**Comment by jcs090218** [comment]
That's awesome! Much better than what I have now! 🚀
