### ISSUE TITLE
Search results not working in Safari Browser (14.0.3)

### ISSUE THREAD

**Issue by reisixx** [thegeeklab/hugo-geekdoc#85]
Hi,
really like your theme, but the search result links are not working in Safari. Am I missing something?

Anyhow, thanks for your effort.

**Comment by xoxys** [comment]
Thanks for your report. Sadly it's hard to debug for me as I don't have an Apple device. Anything in the browser console? Does the hover work and is the target of the link displayed? Or how does it look like?

**Comment by reisixx** [comment]
Can't see anything in the console. The hover (dotted underline) is displayed correctly, but upon click the dropdown closes and nothing happens.
It used to work in the beginning that is why I am using 0.7.3.

**Comment by xoxys** [comment]
@LukasHirt Maybe you have a few minutes to look into this? Any idea?

**Comment by LukasHirt** [comment]
> Maybe you have a few minutes to look into this? Any idea?

@xoxys Sure, I'll take a look :wink:

**Comment by xoxys** [comment]
Ok I was able to reproduce the issue on my machine using Gnome Web Browser which is also using WebKit. Looks like it's a general WebKit rendering issue...

**Comment by xoxys** [comment]
@reisixx CI is preparing v0.10.1 release now. Would be good if you could test it.

**Comment by LukasHirt** [comment]
> CI is preparing v0.10.1 release now. Would be good if you could test it.

You were fast. I did some research as well and it seems that with safari `tabindex` needs to be supplied to the children so that it works correctly. But if it works fine with your solution then great!

**Comment by xoxys** [comment]
@LukasHirt You're right! Setting a tabindex to the `a` elements seems to be working as well. Using tab index it doesn't even matter if it is set correctly or not. Adding `tabindex="0"` to every link is enough to make it clickable.... Do you have a source with some explanations **why** this works or is necessary?

**Comment by LukasHirt** [comment]
> Do you have a source with some explanations why this works or is necessary?

@xoxys Not sure TBH. I have found this suggestion in this stackoverflow https://stackoverflow.com/a/66035686 Somehow it seems that the focus has not been captured on the links which resulted in the dropdown being hidden. Setting the tabindex explicitly specifies that the item is focusable.

**Comment by xoxys** [comment]
Really strange :smile: Anyway, thanks for your research! As `.has-hits:active` seems to have the same effect (keep the focus on the overlay search result list active until the link was really clicked) I'll keep this way for now.
