### ISSUE TITLE
Images referenced relatively not displayed

### ISSUE THREAD

**Issue by edruid** [thegeeklab/hugo-geekdoc#88]
If I have an image in the same directory as the markdown file it is no longer possible to reference it by `![alt](image.png)`. It will render `<img src="/image.png" alt="alt">` rather than `<img src="image.png" alt="alt">` (adding a preceding `/`)

I think removing `relURL` in layouts/_default/_markup/render-image.html will fix it (but I don't know what else might break)

**Comment by edruid** [comment]
My actual setup is that I have the links in the _index.md file from your example (and don't have the my-page.md or if I wanted that page I'd have /content/usage/my-page/_index.md)
Removing `| relURL` worked for me. I took the hint from https://github.com/thegeeklab/hugo-geekdoc/compare/v0.9.1...v0.9.2 doing the same thing for `render-link.html`

I prefer to not clutter static with page specific images (especially since parts, but not all, of my site is behind basic auth)

Using the full path to the images is an option, but then I would not make it relative `!(Example](/usage/example.png)` in case the behavior is changed back later (I'm upgrading from 0.7.3)

**Comment by xoxys** [comment]
Ok so your structure looks like this https://github.com/thegeeklab/hugo-geekdoc/tree/master/exampleSite/content/shortcodes/images. In this case you are right, dropping `relURL` will work.

I'll do some testing later and try to find a way to improve the behavior.
