### ISSUE TITLE
How do I add own fonts and reference them

### ISSUE THREAD

**Issue by eriklilljequist** [thegeeklab/hugo-geekdoc#889]
Hello, I am trying to add my own fonts through static/custom.css

Whatever i try I cannot make my .woff2 fonts in /static/fonts work appear on the site.

the fonts appear in /public/fonts

I try reference them in custom.css as 
@font-face {
    font-family: 'Foobar Sans Headline';
    font-style: normal;
    font-weight: 400;
    src: local(''),
         url('/fonts/foobar.woff2') format('woff2')
}

.gdoc-brand__title {
  font-family: "Foobar Sans Headline";
}

But no luck.

Anyone with a good example on how to add fonts to this theme?

**Comment by xoxys** [comment]
Thanks for your report. There is a small issue in your snippet. You have used an absolute path t your font instead of a relative one:

```
@font-face {
  font-family: "Foobar Sans Headline";
  font-style: normal;
  font-weight: 400;
  src: url("fonts/DancingScript.woff2") format("woff2");
}
```

However, I have created a PR to use custom CSS properties for all default fonts to simplify the usage of custom fonts.

**Comment by eriklilljequist** [comment]
Thank you, I have tried the relative path with no luck so likely I have some additional error.

I will do some more testing... 

But at least you are confirming it should work with the steps I described: add .woff2  to static/fonts and then source them in static/custom.css and then use them in static/custom.css.

**Comment by xoxys** [comment]
What Im wondering about is that if the default fonts are working custom fonts should work as well as the way they are loaded is the same 🤔 what browser are you using?

**Comment by eriklilljequist** [comment]
It works..... I believe there where some extranous parameters in @font-face..  the font face directives came with a zip together with the fonts. 

I removed all but src and  font-family and it started working.

Thank you
