### ISSUE TITLE
Remove space inserted after links

### ISSUE THREAD

**Issue by jcrd** [thegeeklab/hugo-geekdoc#89]
Can the space inserted after links be removed? It looks quite awkward in some situations.
For example:

![image](https://user-images.githubusercontent.com/44040597/113365973-1d4b4300-9315-11eb-9df3-4f49441422e4.png)

**Comment by xoxys** [comment]
Are you using the latest release? This should be fixed already.

**Comment by jcrd** [comment]
Oops, I wasn't on the latest release. It is indeed fixed.
Thanks for this theme and the frequent releases!
