### ISSUE TITLE
Tabs and Hints within a file include arent rendered

### ISSUE THREAD

**Issue by q5sys** [thegeeklab/hugo-geekdoc#90]
I'm not sure that this is really a bug, perhaps its just not possible, but is there anyway to be able to use tabbing and hints from geekdown within an included file?

When I use: 

```{{< include file="static/includes/file.md.part" markdown="true" >}}```

It gets rendered as markdown and none of geekdocs shortcodes get processed.  Is there a way I can edit one of the config files or tweak something else so that shortcodes will work?  Single location sourcing is super helpful and I'd like to be able to use it as effectively as possible.

**Comment by xoxys** [comment]
Thanks for your report! Indeed, the `readFile` function in Hugo does not render shortcodes. The only way to achieve this seems to be using regular Hugo pages. I've already prepared a PR, this feature will be included in the next release.
