### ISSUE TITLE
`hugo --minify` breaks spaces in breadcrumb

### ISSUE THREAD

**Issue by TR-SLimey** [thegeeklab/hugo-geekdoc#91]
When building a site with this template using the `--minify` option, some spaces are removed, which is especially noticeable in the breadcrumb at the top of the page. I wonder if this could be worked around somehow?

**Comment by xoxys** [comment]
Thanks for your report! Please see https://github.com/thegeeklab/hugo-geekdoc/issues/81. I will at least include this in the documentation.

**Comment by TR-SLimey** [comment]
Ah, I should have checked existing issues more thoroughly. That's understandable, thanks!

**Comment by TR-SLimey** [comment]
I've got an idea and I have no clue if it would work because I didn't look at the codebase at all, but what if you were to replace spaces with other types of whitespace of equal width? Maybe they would get ignored by Hugo?

**Comment by xoxys** [comment]
Sure, that might or might not work as expected but I dont really like to mess around with unicode chars in the theme. I still think most of the issues should be fixed upstream.
