### ISSUE TITLE
Improve the look of the scrollbar

### ISSUE THREAD

**Issue by jcs090218** [thegeeklab/hugo-geekdoc#912]
The scrollbar doesn't look very good at the moment.

![2024-11-09 21 49 52](https://github.com/user-attachments/assets/cf814954-30bd-48c7-bbe2-1f4f3f537423)

It might be a good idea to improve the look of it.

**Comment by xoxys** [comment]
Im not a fan of scrollbar theming and would like to keep the style of the browser, sorry.
