### ISSUE TITLE
Option to exclude page from search results

### ISSUE THREAD

**Issue by edruid** [thegeeklab/hugo-geekdoc#95]
Background:
In my setup parts of the page is set up behind authentication while the search isn't. The search itself then becomes a security issue as the search-data file contains most of the information of those secured pages if they are included in the search.

Proposed solution:
Add the ability to add a page variable (geekdocSkipSearch: true?) marking the page as being ignored by search.
Change line 2 in themes/geekdoc/assets/search-data.json to
```
{{ range $index, $page := (where .Site.Pages "Params.geekdocSkipSearch" "!=" true) }}
```

**Comment by xoxys** [comment]
I've changed the new parameter to a more generic one as there might be more data files to handle like atom/rss feeds in the future where it might be required to exclude those pages.

**Comment by xoxys** [comment]
@edruid What do you think? Does it make any sense for you?

**Comment by edruid** [comment]
That will work fine, thanks! Sorry for not responding earlier (email notification was lost in too many unread emails)

**Comment by xoxys** [comment]
No worries. Thanks for your feedback.
